NVIDIA/DIGITS

- digits-devserver
- digits-walkthrough
- digits/config.py
- tools/create_db.py
- tools/parse_folder.py
- tools/resize_image.py
I was having trouble running the scripts as executables because it was using #!/usr/bin/python instead of the python in my PATH. This updates the shebang line to #!/usr/bin/env python for all of the executable python files.
> changed shebang line in executable python files 

- digits/model/forms.py
- digits/model/images/classification/test_views.py
- digits/model/images/classification/views.py
- digits/templates/models/images/classification/new.html
- digits/templates/models/images/classification/show.html
1) Removed the select field for previous networks snapshots from forms.py, due to wtforms validation issues. Then included code in views.py and new.html, to display the select fields for previous networks snapshots in html and for validating these fields. These changes fix the pretrained model selection bug. Also these changes ensure the display of error message, incase user selects the job that doesn't exists (this scenario happens when a user selects the job and at the same if another user deletes this job)
2) fix to the following issue: when validation fails, the selected radio buttons in "previous networks" tab remains selected but the select input field and customize button beside the selected previous network is in hidden status, which is wrong. same issue exists in standard …
> Fixed issue#1: pretrained model selection bug

- digits/templates/datasets/images/classification/new.html
If I interprete [titles.append(labels[int(key)]](https://github.com/NVIDIA/DIGITS/blob/master/digits/dataset/tasks/create_db.py#L243) correctly then the then numeric labels start at 0 and line numbers at 1.
> Correction of tooltip for labels file

- docs/TorchInstall.md
Fix markup and add environment variable suggestion
Remove a bunch of unnecessary explanations
Move LMDB instructions to the bottom
> Simplify torch install instructions

- digits/dataset/tasks/create_db.py
- tools/create_db.py
- tools/test_create_db.py
@crohkohl partially addressed this in #199 for the sake of platforms where LevelDB isn't supported. This takes his partial solution to its logical extension. You can't actually use LevelDB with DIGITS anyway, so I think we should just go ahead and remove all references to it.
> Remove all references to LevelDB

- digits/templates/home.html
- digits/views.py
- docs/API.md
- docs/FlaskRoutes.md
This is just a quick fix until we get a proper job management page.
It shows you how many GPUs are available for training on this server (see top right).
> Add widget to the homepage showing available gpus

- scripts/travis/install-caffe.sh
Travis started failing with this error:
File "/home/travis/miniconda/lib/python2.7/os.py", line 157, in makedirs
mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/home/travis/.cache/pip/wheels/b7'
https://travis-ci.org/NVIDIA/DIGITS/builds/75335608
I fixed this by chowning all of `~/.cache` to travis:travis. This is admittedly pretty lazy. I should probably figure out which package changed, but I don't have time at the present.
> TravisCI fixes

- digits/dataset/images/generic/test_lmdb_creator.py
- requirements.txt
- tools/create_db.py
- tools/test_create_db.py
*Closes #206.*
* Don't set the initial map_size to 1TB like before
* It seems to start with 10MB by default
* When LMDB throws a MapFullError, double the map size
* Big thanks to @dw for https://github.com/dw/py-lmdb/commit/442096e1551e204894154436877080a5b2571813
> Double LMDB map_size on MapFullError

- digits/model/images/classification/test_views.py
- digits/model/job.py
Ahmed pointed out that the REST API doesn't expose any information about which `DatasetJob` a `ModelJob` depends on.
> Add dataset_id to ModelJob's JSON representation

- digits/templates/datasets/images/classification/new.html
- digits/templates/datasets/images/generic/new.html
- digits/templates/helper.html
- digits/templates/models/images/classification/new.html
- digits/templates/models/images/generic/new.html
I tried to find a way to use the field.label in the error messages, but couldn't make that work.  I thought the next best thing would be pretty up the field name. So that crop_size becomes Crop Size.  Looks a little cleaner. Many of the field names are very close to the field.label.  Some are way off.
> Make alert box into a macro and try to prety up the field name

- digits/model/tasks/caffe_train.py
Reported at https://groups.google.com/d/msg/digits-users/OMLQC38t-L4/Pn01UvFZJAAJ
I'm currently refactoring these `save_files()` functions so as to share code between the classification and generic paths, and also to be able to write tests for them. Look for another PR soon with the refactoring and tests. This is a quick fix for a specific problem.
> Fix layer.top checking for generic models

- digits/templates/datasets/images/classification/show.html
To avoid broken-image icon being displayed as mean image file
not yet created.
> Don't show mean image during dataset creation

- digits/model/images/classification/test_views.py
- digits/model/tasks/caffe_train.py
Thanks to @RadicoLabs for reporting this bug (several times):
* https://github.com/NVIDIA/DIGITS/issues/234
* https://github.com/BVLC/caffe/issues/2965
* https://groups.google.com/d/msg/digits-users/fv1lcvvmXNE/QXPl7qCPJQAJ
I introduced a bug in f3cee358fa1105d96b5ddd9cc6fd2aa9db3a5857 that wasn't caught by the test suite. I introduced an additional axis to the shape of the data. The reason this wasn't caught is because the `InnerProduct` layer in the deploy network saw the same number of neurons in the previous layer as it did during training - `10x1x10x10` ~= `10x1x1x10x10`. Convolution layers, however, check for the number of axes and throw an error. 
This commit fixes the bug and adds a test class which uses LeNet (including Convolution layers).
> Bugfix - wrong shape calculated for infer_many

- digits/model/tasks/caffe_train.py
See https://github.com/BVLC/caffe/pull/2950 - the examples were leading me astray.
This doesn't break backwards-compatibility with old models. It just starts generating `deploy.prototxt` in the recommended way.
> Use input_shape instead of input_dim for deploy

- docs/API.md
- docs/FlaskRoutes.md
- scripts/generate_docs.py
With this change, you'd still have to run `scripts/generate_docs.py` when (1) adding or removing a route or (2) changing a filename, but not when simply adding a line to a function in a view. It was a cool feature, but not worth the headache.
> Remove line number from autodoc files

- digits/templates/models/images/classification/show.html
- digits/templates/models/images/generic/show.html
Fix for #244.
The form is hidden until the first model snapshot.
> Move "Trained Models" text inside form

- digits/dataset/images/generic/forms.py
- digits/dataset/images/generic/test_views.py
- digits/dataset/images/generic/views.py
- digits/dataset/tasks/analyze_db.py
- digits/templates/datasets/images/generic/new.html
- digits/templates/datasets/images/generic/show.html
- tools/analyze_db.py
- tools/test_analyze_db.py
> Improvements for analyze_db tool

- requirements_test.txt
- scripts/generate_docs.py
`v0.1.2` [was released](https://github.com/acoomans/flask-autodoc/releases/tag/0.1.2) this week, including grouping fixes (https://github.com/acoomans/flask-autodoc/commit/e4d58f4cb4d75f0b0bd8f93524eba98a6d8b6a9f) and file location information (https://github.com/acoomans/flask-autodoc/pull/17). Let's use it instead of my custom version.
> Use Flask-Autodoc v0.1.2

- README.md
*See https://github.com/landscapeio/landscape-issues/issues/179*
Let's remove the icon (which fails to load) from the README. When/if the website comes back up, we'll still be able to access it at https://landscape.io/github/NVIDIA/DIGITS without the badge.
> Remove Landscape.io badge

- digits/job.py
- digits/templates/job.html
- digits/views.py
- docs/API.md
- docs/FlaskRoutes.md
Now, notes can be added for every job. Also, the user can update the notes. Let me know if any changes are required.
> Notes functionality added for every Job

- digits/dataset/images/classification/forms.py
- digits/dataset/images/classification/views.py
- digits/dataset/images/views.py
- digits/dataset/job.py
- digits/dataset/tasks/create_db.py
- digits/model/tasks/caffe_train.py
- digits/templates/datasets/images/classification/new.html
- digits/templates/datasets/images/classification/show.html
- digits/templates/datasets/images/classification/summary.html
- docs/API.md
- docs/FlaskRoutes.md
- tools/create_db.py
- tools/test_create_db.py
*Closes #224*
* Allow non-image data (see #197)
* Analyze prebuilt HDF5 datasets in "generic" path
> Add support for HDF5 datasets

- tools/create_db.py
- tools/test_create_db.py
@gheinrich mentioned that the tests were still failing on Ubuntu 12. This should fix the issue.
> Fix data sharding in HDF5 files

- digits/templates/models/images/classification/new.html
- digits/templates/models/images/generic/new.html
Fix bug introduced in 66d8404713b0fa94f84a33a2cf4031fa20e6aa3c for `ClassificationJobs` - the snapshot list for the first job on the second page was really the list for the first job on the first page.
Add pagination for `GenericJobs`. It wasn't added with 66d8404713b0fa94f84a33a2cf4031fa20e6aa3c.
> Fix previous network snapshot lists

- digits/dataset/tasks/create_db.py
If you switch around between different versions of the code, the backend
field can get set to None and that breaks things. This is a more
explicit check.
> Fix create_db_task.backend == None scenario

- digits/dataset/images/classification/job.py
- digits/dataset/images/generic/job.py
- digits/dataset/job.py
- digits/dataset/tasks/analyze_db.py
- digits/templates/datasets/images/classification/summary.html
- digits/templates/datasets/images/generic/summary.html
- digits/templates/home.html
note: doesn't show a badge for generic datasets
> Show DB backend on home and model creation pages

- digits/utils/image.py
We should take the floor of `dim*ratio` when calculating the size of the upscaled image. In some cases where the ratio is not numerically correct, taking the ceiling of `dim*ratio` will result in a slightly larger image than expected. For example if the minimum required dimension is 100 and an image with a minimum dimension of 78 must be upscaled:
```
>>> min_img_dim=100
>>> min_dim=78
>>> ratio=float(min_img_dim)/min_dim
>>> ratio
1.2820512820512822
>>> ratio*min_dim
100.00000000000001
>>> math.ceil(ratio*min_dim)
101.0
```
If we take the ceiling of `ratio*min_dim` then the resulting dimension in the upscaled image  is 101, as opposed to the expected 100. This can result in out-of-band read from the input image later on when populating the upscaled image matrix.
> Fix rounding bug introduced by 80e3330

- digits/dataset/images/classification/test_views.py
- digits/dataset/images/generic/test_views.py
- digits/model/images/classification/test_views.py
- digits/model/images/generic/test_views.py
TravisCI builds have started timing out sometimes (https://github.com/NVIDIA/DIGITS/pull/331#issuecomment-143792884). Since the build machines don't have GPUs, Caffe takes a LOT longer to run.
> Increase test timeouts (TravisCI can be slow)

- digits/config/caffe_option.py
- requirements.txt
Previously, it totally failed to parse "0.14.0-alpha", which is valid semantic versioning.
This PR uses `pkg_resources` from `setuptools` to do the comparison.
\<rant>
Technically, `setuptools` adheres to [PEP 440](https://www.python.org/dev/peps/pep-0440/) and not [Semantic Versioning 2.0.0](http://semver.org/spec/v2.0.0.html), but I can't find any package/tool which (1) actually follows Semantic Versioning correctly when the version is correct, and (2) still does something useful when it's a little bit off.
Things I tried which don't work quite right:
* raw string comparisons
* git built-in (`git tag`)
* GitHub
* `distutils.version.LooseVersion`
* `semantic_version.Version`
* `pkg_resources.parse_version` (close enough)
https://gist.github.com/lukeyeager/9922a2229f7a03d1463c
\</rant>
> Allow DIGITS to parse NVcaffe version strings

- docs/InstallCaffe.md
You can still copy+paste the command. But now you can see it all in one line and follow the list of packages in their logical progression.
> Reorder apt-get packages into logical progression

- digits/dataset/images/classification/test_views.py
- digits/dataset/images/generic/test_views.py
- digits/model/images/classification/test_views.py
- digits/model/images/generic/test_views.py
- requirements_test.txt
There were a lot of warnings like this in the build logs:
/home/travis/miniconda/lib/python2.7/site-packages/bs4/__init__.py:166: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.
To get rid of this warning, change this:
BeautifulSoup([your markup])
to this:
BeautifulSoup([your markup], "html.parser")
markup_type=markup_type))
ok
> Suppress annoying BeautifulSoup warning

- digits/dataset/images/classification/test_views.py
- digits/dataset/images/classification/views.py
- digits/static/css/style.css
- digits/templates/datasets/images/classification/explore.html
- digits/templates/datasets/images/classification/show.html
- digits/utils/image.py
- docs/API.md
- docs/FlaskRoutes.md
*Closes #21*
Implemented some way to visualize a dataset db as a gallery, solving #21. I did that to debug #330, as some transformations were not doing what I expected. 
You can browse a dataset page by page, reading directly from the db. For now it's only working with lmdb . You can filter by one of the labels from the classification task, as well as change the number of images displayed. 
The explorer is accessible from a button in the dataset show view, once a task is done. 
The UI is a bit rough and can probably be improved but at least it's functional. 
I'll write some tests when I have enough time.
> Dataset visualization

- digits/standard-networks/torch/lenet.lua
On MNIST (1x28x28, 45k training images, 15k validation images),
with batch size of 64.
Training time for 20 epochs:
Original: 8m26s
With CuDNN: 3m7s
> Torch7/LeNet: use cudnn when available

- digits/model/tasks/caffe_train.py
Upstream caffe decided to use the "--gpu" flag instead of the original "--gpus" flag which was merged into NVcaffe.
> Use new multi-GPU flag for NVcaffe v0.14

- digits/dataset/images/generic/test_lmdb_creator.py
- scripts/generate_docs.py
- scripts/test_generate_docs.py
- tools/analyze_db.py
- tools/create_db.py
- tools/parse_folder.py
- tools/resize_image.py
If you have the digits package installed globally (on your PYTHONPATH)
and you try to run a local DIGITS instance, the tools pick up the global
installation instead of the local one when you start them in a new
process. This patch fixes the issue.
NOTE: in the future, this should be handled by moving the tools scripts
inside the digits package. This is a short-term solution.
> Stop tools from importing global DIGITS install

- digits/dataset/images/classification/test_views.py
- digits/dataset/images/generic/test_views.py
- digits/model/images/classification/test_views.py
- digits/model/images/generic/test_views.py
Cherry-picking commit from https://github.com/NVIDIA/DIGITS/pull/345#issuecomment-147235679.
This is a one-up for https://github.com/NVIDIA/DIGITS/pull/332.
> Increase timeouts

- digits-server
- digits-test
Previously, if you didn't have nosetests installed, ./digits-test would
fail like this:
$ ./digits-test
Unknown option: --
usage: /home/lyeager/digits/venv/bin/python [option] ... [-c cmd | -m
mod | file | -] [arg] ...
Try `python -h' for more information.
Now, it would fail like this:
$ ./digits-test
ERROR: "nosetests" executable not found!
> Fix checks in bash script to throw useful errors

- digits/model/tasks/caffe_train.py
*Fix #255, Fix #349*
Previously, `scores = output` performed a shallow copy that was
overwritten when the next output was calculated. Now, we're using
`np.copy` to do a deep copy and avoid the error.
> Fix infer_many for Caffe

- digits/model/images/classification/test_views.py
- digits/model/images/classification/views.py
If you upload a file like:
/path/to/image1.jpg 100
To a model with only 10 classes, DIGITS would throw an error. This patch
sets the ground truth for that image to None instead.
> Ignore invalid ground truth for classify_many

- digits/model/images/classification/views.py
@gheinrich in #249 you added this try/except block for `InferenceError`s. Why?
Current behavior for errors:
After this change, it matches the format for other exceptions:
In debug mode, you get more information:
> Display InferenceErrors like all other exceptions

- digits/frameworks/torch_framework.py
- digits/model/tasks/torch_train.py
- digits/utils/test_filesystem.py
When running the image classification model tests like this:
./digits-test digits/model/images/classification/test_views.py
the number of open files for the test suite grows to > 900. You can verify this with:
while :; do lsof -p $PID | grep tmp | wc -l; sleep 1; done
where PID is the process ID of the test suite.
This patch brings the number of open files down from > 900 to ~90. There's more work to be done to fix this completely, but this takes a big step in the right direction.
NOTE: I can't actually run the whole testsuite or I get a bunch of these OSErrors:
OSError: [Errno 24] Too many open files
> Fix some of the open file issues with Torch

- tools/torch/data.lua
Variable name conflict prevents from loading HDF5 datasets that spread across several databases.
This is a regression and it was introduced with 13d28b4079 (#345).
> Fix Torch HDF5 loading from multiple databases

- digits/model/tasks/torch_train.py
- digits/standard-networks/torch/ImageNet-Training/alexnet.lua
- digits/standard-networks/torch/ImageNet-Training/googlenet.lua
- digits/standard-networks/torch/lenet.lua
- docs/InstallTorch.md
- tools/torch/main.lua
The default batch size in the DIGITS is 16. This change allows specification of different batch sizes from Torch model descriptions for the training and validation phases.
Also align batch sizes of Torch standard networks with Caffe standard networks.
Using MNIST (45k training samples, 15k validation samples) and LeNet (20 epochs):
default batch size (16): 190s
default batch size from model (training: 64, validation: 100): 118s
Using CIFAR10 (images upscaled to 256x256):
Alexnet (2 epochs) default batch size (16): 1230s
Alexnet (2 epochs) batch size from model (100): 948s
GoogLenet (2 epochs) default batch size (16): 5340s
GoogLenet (2 epochs) batch size from model (24): 5280s
> Torch: support batch size specification in model file

- digits/model/images/classification/test_views.py
- digits/model/images/generic/test_views.py
Setting weights and biases to zero initially. This applies to the
model used in all Torch classification tests except those that use
the standard LeNet model.
Tested with:
./digits-test -v --with-coverage --cover-package=digits -s --tests=digits.model.images.classification
Without patch:
10 failures / 128 iterations
With patch:
1 failure / 160 iterations
Note: the one failure was on a test that uses the LeNet model,
which isn't modified by this patch. That failure has to do with
the pretty aggressive learning rate policy, which is set to 'fixed'
for this test. Log shows model learning up to 100% validation
accuracy then regressing to 66% accuracy on last epoch.
see bug #346
> Use fixed seed in model tests

- digits/dataset/images/classification/test_views.py
- digits/dataset/images/classification/views.py
- digits/dataset/images/generic/test_views.py
- digits/dataset/images/generic/views.py
- digits/model/images/classification/test_views.py
- digits/model/images/classification/views.py
- digits/model/images/generic/test_views.py
- digits/model/images/generic/views.py
- digits/templates/datasets/images/classification/new.html
- digits/templates/datasets/images/generic/new.html
- digits/templates/helper.html
- digits/templates/job.html
- digits/templates/models/images/classification/new.html
- digits/templates/models/images/generic/new.html
- digits/utils/forms.py
- digits/utils/routing.py
- digits/views.py
- docs/API.md
- docs/FlaskRoutes.md
A 'Clone Job' button has been added to the Job pages.  
The approach I took was to save the form settings when a job starts for each Field (except SubmitField and FileField in a dict() on the job called form_data.
When a job is cloned, the form is created and populated with the saved form_data from the source job.  If a field in the form can not be populated with saved form_data, a warning is presented at the head of the document.
I put the 'Clone Job' button to the left of the 'Abort Job' button.  
I'd don't love this. When the Job completes, the 'Abort Job' disappears and the Clone moves to where the Abort Job had been, and could fire a Clone when the user means to Abort.  Also, if the source job does not have form_data, the 'Clone Job' button is disabled rather then hidden.  I'm not …
> Add ability to clone previous jobs

- digits/model/tasks/caffe_train.py
*Fix #377*
Don't print the traceback - print the raw output.
> Print raw caffe output for failed tests

- digits/model/images/classification/test_views.py
- digits/model/images/classification/views.py
- digits/model/images/forms.py
- digits/model/images/generic/test_views.py
- digits/model/images/generic/views.py
- digits/model/tasks/caffe_train.py
- digits/model/tasks/torch_train.py
- digits/model/tasks/train.py
- tools/torch/data.lua
- tools/torch/main.lua
- tools/torch/test.lua
> Make it optional to subtract mean pixel or mean image

- .travis.yml
On DIGITS ToT, Travis logs are close to 4MB in size, which is the
hard limit for log size on Travis. Longer logs would yield an error.
This change causes the Torch7 install log to only be printed on an
install error.
This reduces the size of a typical log down to 250kB and 4000 lines,
meaning that the full log can be displayed in real time since it is
less than 10,000 lines.
> Reduce Torch7 install verbosity

- digits/model/images/classification/views.py
- digits/model/images/generic/views.py
When using 'crop in form' method, images are cropped in Python
code before 'classify one'. This is slightly inconsistent as
this operation is not performed during training or in the
context of 'classify many'. Besides, this is problematic for
Torch (at least) since the mean image is not cropped and this
makes it difficult to perform mean subtraction during 'classify
one' as the input and mean image have different sizes.
Caffe uses the 'crop_size' option in the data layer transformations.
Similarly, for Torch the crop command-line flag may be used to
crop the image within Torch. Either way, it is not necessary
to crop the image in Python code.
> Don't crop image before feeding to DL framework

- .travis.yml
This reverts commit a25e13acd0c24178a18012a706505f57eaeb894d (#394).
We may redo it differently with #396, but we need to just revert it for now.
> Revert "Reduce Torch7 install verbosity"

- gunicorn_config.py
- nginx.site
Port 8080 is a fairly common debugging port. Switch to using 34448 instead (that's "DIGIT" on an old-school phone).
The user shouldn't need to be aware of the port at all, since digits-server is intended to run behind an nginx reverse proxy (see nginx.site).
> Use port 34448 (DIGIT) for digits-server, not 8080

- digits/model/forms.py
- digits/model/images/classification/test_views.py
- digits/model/images/classification/views.py
- digits/model/images/generic/views.py
- digits/task.py
- digits/templates/models/images/classification/new.html
- digits/templates/models/images/generic/new.html
- digits/utils/filesystem.py
- scripts/travis/install-caffe.sh
Copies the python file to the job directory from the server of the client.
> Add widget to copy python file from client or server to job dir

- .travis.yml
- scripts/travis/install-torch-wrapper.sh
As suggested by @lukeyeager prepending the install command
with `travis_wait` will print a log message every minute
for 20 minutes, allowing Torch install to take a little more
than the usual <10 minutes.
> Reduce Torch install verbosity

- requirements.txt
https://groups.google.com/d/msg/digits-users/_6xGrd_FmHA/YYrG4AVFAQAJ
```
$ ./digits-server
Error: class uri 'socketio.sgunicorn.GeventSocketIOWorker' invalid or not found: 
[Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 132, in load_class
mod = __import__('.'.join(components))
ImportError: No module named socketio.sgunicorn
]
```
Somebody upgraded their pip package on PyPI and now the standard DIGITS install instructions don't work.
I suspect the culprit is Flask-SocketIO v0.6 -> v1.0.
The fix in this pull request worked for that specific user and for me, but I haven't had the time to debug this properly yet.
> Update list of requirements to force Flask-SocketIO==0.6.0

- digits/model/tasks/torch_train.py
- tools/torch/logmessage.lua
- tools/torch/wrapper.lua
Introduce a wrapper script to catch and report errors
in a more straightforward way. The main error is now
shown on the job summary window, in big, red letters.
> Torch - report error on job summary

- tools/torch/data.lua
- tools/torch/utils.lua
The labels.txt file used to map class names to class IDs might
contain line endings that could confuse the parser during inference.
> Trim whitespaces off of labels file

- digits/model/tasks/train.py
*Fixes a bug from #321*
When upgrading `TrainTasks` from before #321, we need to update the `use_mean` field accordingly.
To reproduce the bug:
1. `git checkout v2.2.1` and start up the server
2. Create a new classification model job
3. Verify that classifying an image works correctly
4. Shut down the server, `git checkout v3.0.0-rc.1` and start up the server again
5. Try classifying an image with the same model
> Fix the upgrade path for TrainTask.use_mean

- tools/torch/data.lua
This allows passing tensors between threads by
reference. This speeds up training for all models,
particulary when data are comparatively large
v.s. compute time.
Alexnet on CIFAR10 (2 epochs): 10m35s -> 9m28s
GoogleNet on CIFAR10 (1 epoch): 45m5s -> 44m52s
LeNet on MNIST (30 epochs): 2m17s -> 2m15s
> Enable shared serialization in Torch

- digits/model/images/classification/test_views.py
- digits/model/tasks/caffe_train.py
- digits/utils/filesystem.py
This addresses a bug from https://github.com/NVIDIA/DIGITS/pull/329. Without this fix, you can train a model with a PythonLayer, but you can't test it.
```
SystemError
NULL result without error in PyObject_Call
File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/home/lyeager/digits/digits/model/images/classification/views.py", line 291, in image_classification_model_classify_one
predictions, visualizations = job.train_task().infer_one(image, snapshot_epoch=epoch, layers=layers)
File "/home/lyeager/digits/digits/model/tasks/caffe_train.py", …
```
> Make python layers work for inference

- README.md
*Reverts commit 4bb2c4e7cb917ffc2b27bac94b33843f0d759604 from https://github.com/NVIDIA/DIGITS/pull/276.*
Now that https://github.com/landscapeio/landscape-issues/issues/179 is fixed, let's turn the badge back on.
I'm also going to look into turning the GitHub integration back on now that https://github.com/landscapeio/landscape-issues/issues/160 is fixed.
> Revert "Remove icon for Landscape.io"

- .travis.yml
TravisCI is migrating to Ubuntu 14.04 (trusty) from 12.04 (precise) - https://github.com/NVIDIA/DIGITS/issues/213#issuecomment-141532763. Let's be explicit about which version we're expecting.
> https://gist.github.com/meatballhat/d0c8aab9e3bd8a8bcacd
I've opened a related PR for Caffe at https://github.com/BVLC/caffe/pull/3407.
We'll wait for NVcaffe to transition to `trusty` before trying it with DIGITS.
> Mark the expected TravisCI distro explicitly

- docs/UbuntuInstall.md
Lots of people are trying to use the deb packages and complaining - https://github.com/NVIDIA/DIGITS/issues/427, https://github.com/NVIDIA/DIGITS/issues/433, https://github.com/NVIDIA/DIGITS/issues/435, https://github.com/NVIDIA/DIGITS/issues/451.
They should be ready soon! Until then, let's make the situation clear on the `master` branch.
> Mark Ubuntu instructions not ready yet

- digits/standard-networks/torch/ImageNet-Training/alexnet.lua
- Move to "1-tower" architecture,
- Enable CuDNN fastest mode,
- Remove unnecessary input grad computations on first layer
- Use optimal backend for SoftLogMax layer
This model trains more quickly than the previous model:
14m3s -> 10m35s (two epochs on 256x256 upscaled CIFAR10).
> Update Torch Alexnet reference model

- digits/model/images/classification/test_views.py
- digits/model/images/generic/test_views.py
By default Caffe zero-initialises weights and biases for linear
layers (http://caffe.berkeleyvision.org/tutorial/layers.html).
Torch on the other hand initializes linear layer parameters by
picking from a uniform distribution.
For the problem that we are trying to solve in the automatic
tests it is quicker to train from zero-initialised weights
as we only really need to learn the sign of those parameters.
> Set linear weights to zero in automatic tests

- digits-devserver
- digits-server
- digits-test
- digits/config/edit.py
- digits/dataset/images/classification/test_imageset_creator.py
- digits/dataset/images/generic/test_lmdb_creator.py
- digits/device_query.py
- examples/classification/example.py
- examples/classification/use_archive.py
- scripts/generate_docs.py
- tools/analyze_db.py
- tools/create_db.py
- tools/download_data/main.py
- tools/parse_folder.py
- tools/resize_image.py
- tools/test_resize_image.py
> in preparation for an eventual change in the default version of Python, Python 2 only scripts should either be updated to be source compatible with Python 3 or else to use python2 in the shebang line.
https://www.python.org/dev/peps/pep-0394/
> Use python2 in shebang lines - PEP 394

- tools/torch/main.lua
Original (20 epochs LeNet on MNIST): 187s
Now: 142s
Helps with bug #339
> Make unnecessary computations optional

- digits/model/images/classification/test_views.py
- digits/standard-networks/torch/ImageNet-Training/alexnet.lua
- digits/standard-networks/torch/ImageNet-Training/googlenet.lua
- digits/standard-networks/torch/lenet.lua
- docs/GettingStartedTorch.md
- tools/torch/main.lua
- tools/torch/test.lua
- tools/torch/utils.lua
Allow networks to select desired number of outputs depending on
number of classes in (classification) dataset.
Stop automatically adjusting number of outputs in Lua wrappers.
This is less confusing and this will make it easier to enable
multi-GPU training with Torch in DIGITS.
> Export number of classes to Torch models

- tools/create_db.py
Before this fix, you had to explicitly specify `--hdf5_dset_limit=2147483648` to avoid this error:
```sh
$ tools/create_db.py train.txt train_db 28 28 -b hdf5
2015-12-09 09:18:40 [WARNING] removing existing database
2015-12-09 09:18:40 [DEBUG] 7502 total lines in file
2015-12-09 09:18:40 [INFO ] 7502 valid lines in file
2015-12-09 09:18:40 [DEBUG] Category 0 has 735 images.
2015-12-09 09:18:40 [DEBUG] Category 1 has 851 images.
2015-12-09 09:18:40 [DEBUG] Category 2 has 774 images.
2015-12-09 09:18:40 [DEBUG] Category 3 has 758 images.
2015-12-09 09:18:40 [DEBUG] Category 4 has 737 images.
2015-12-09 09:18:40 [DEBUG] Category 5 has 669 images.
2015-12-09 09:18:40 [DEBUG] Category 6 has 719 images.
2015-12-09 09:18:40 [DEBUG] Category 7 has 771 images.
2015-12-09 09:18:40 [DEBUG] Category …
```
> Set default HDF5 filesize limit in create_db tool

- digits/model/tasks/torch_train.py
Same as #383, but now for Torch.
Helps with debugging failed tests.
> Print torch output for failed tests

- digits/templates/datasets/images/generic/show.html
- digits/templates/models/images/classification/show.html
- digits/templates/models/images/generic/show.html
*Close #467*
As suggested by @GiuliaP, show the job directory for all job types, not just `ImageClassificationModelJobs`.
> Show job_dir on all job pages

- digits/templates/job_row.html
Apparently HTML has no problem with unmatched parentheses - I only noticed because it messed up the syntax highlighting in my editor.
Looks like this is coming from #240. @jmancewicz please confirm and merge if this look OK.
> Fix typo in template

- digits/dataset/images/generic/test_views.py
Since the generic test suite all uses the same LMDBs, we can just create them once rather than re-creating them for each test class.
Command:
```sh
./digits-test digits/*/images/generic/ -s -v
```
Before:
```
153 tests run in 223.1 seconds.
3 skipped (150 tests passed)
```
After:
```
153 tests run in 156.3 seconds.
3 skipped (150 tests passed)
```
> Speedup generic tests

- digits/model/images/classification/test_views.py
- tools/torch/data.lua
Unencoded LMDB data are stored in BGR format so a
channel swap is required to have a consistent
representation of data across inputs, mean files,
etc.
> Fix handling of unencoded LMDB in Torch

- tools/torch/data.lua
Commit f710c5f failed to properly initialize the blue channel
when loading data from unencoded LMDB. Instead the blue channel
was initialized with the contents of the red channel. This was
ironically enough to pass the classification tests since the
'blue' class was effectiveley the only class with all zeroes.
> Fix init of blue channel in unencoded LMDB

- digits/scheduler.py
Matches what we do [when deleting a job](https://github.com/NVIDIA/DIGITS/blob/v3.0.0-rc.3/digits/scheduler.py#L269).
You ought to be able to grep the log for all relevant events for a job like this:
```sh
$ cat digits/digits.log | grep 20151228-131316-6a72
2015-12-28 13:13:18 [20151228-131316-6a72] [INFO ] Train Caffe Model task started.
2015-12-28 13:13:21 [20151228-131316-6a72] [INFO ] Job aborted.
2015-12-28 13:13:24 [20151228-131316-6a72] [INFO ] Job deleted.
```
> Add log message when aborting a job

- digits/frameworks/torch_framework.py
- digits/model/images/classification/test_views.py
- digits/model/tasks/torch_train.py
- digits/standard-networks/torch/ImageNet-Training/alexnet.lua
- digits/standard-networks/torch/ImageNet-Training/googlenet.lua
- digits/standard-networks/torch/lenet.lua
- digits/templates/models/images/classification/new.html
- docs/BuildTorch.md
- docs/GettingStartedTorch.md
- tools/torch/Optimizer.lua
- tools/torch/main.lua
*Close #138*
This commit enables data parallelism, i.e. train
batches are evenly spread across selected GPUs.
Strong scaling is applied by default, i.e. batch
size is unchanged and each GPU receives its share
during training.
For better performance, installation of the NCCL
module is recommended.
On a 2xTitanX machine (with NCCL):
- GoogleNet: 51m4s (1 GPU) -> 34m3s (2 GPUs)
- Alexnet: 12m31s (1 GPU) -> 10m38s (2 GPUs)
- LeNet*: 53s (1GPU) -> 1m30s (2 GPUs)
* the overhead of inter-GPU communication seems to
outweigh the compute gain on LeNet
> Torch Multi-GPU support

- tools/create_db.py
*Fixes #254 (coming from #245)*
Improves CPU utilization when creating encoded LMDB datasets.
Tools used to debug: [cProfile](https://docs.python.org/2/library/profile.html).
> Move image encoding out of main create_db thread

- digits/device_query.py
Makes `device_query.py` more useful. Previously, the output was 159 lines long (on my machine with 3 GPUs). Output is now 42 lines, with a `--verbose` option that allows you to see all the information if you still really need it.
```
$ ./device_query.py 
Device #0:
>>> CUDA attributes:
name                         GeForce GTX TITAN Z
totalGlobalMem               6432907264
clockRate                    875500
major                        3
minor                        5
>>> NVML attributes:
Total memory                 6134 MB
Used memory                  771 MB
Memory utilization           2%
GPU utilization              9%
Temperature                  45 C
Device #1:
>>> CUDA attributes:
name                         GeForce GTX TITAN Z
totalGlobalMem               6442254336
clockRate …
```
> Display enhancements for device_query.py

- tools/test_analyze_db.py
Like with #508, need to import `digits.config` before importing `caffe_pb2` in order to run this test file by itself.
./digits-test tools/
> Fix another import bug from #501

- digits/config/test_config_file.py
- digits/config/test_prompt.py
- digits/model/tasks/test_caffe_train.py
- digits/test_device_query.py
- digits/test_scheduler.py
- digits/utils/test_image.py
- tools/test_analyze_db.py
- tools/test_create_db.py
- tools/test_parse_folder.py
- tools/test_resize_image.py
It's supposed to refer to a throwaway variable, not the most relevant package in the test suite.
This is a non-functional change.
> Don't use "_" for package names in testsuite

- digits/model/forms.py
- digits/model/tasks/caffe_train.py
I've added an option to copy weights from multiple pretrained networks so that ensembles can be built easily. Multiple pretrained networks can be added as semicolon delimited paths.
> Add option to use multiple pretrained networks

- digits/model/images/classification/test_views.py
- digits/model/images/classification/views.py
- digits/model/images/generic/test_views.py
- digits/model/images/generic/views.py
- digits/templates/models/images/classification/show.html
- digits/templates/models/images/generic/show.html
> Allow optional specification of image folder during multiple inference

- nginx.site
*Fix #528*
After using `dpkg-reconfigure` to change the reverse proxy front-end port from 80 to something else (e.g. 5000), redirects were still going back to port 80.
~~Solution based on answers to [this SO post](http://serverfault.com/questions/576365/use-nginx-reverse-proxy-for-redirection).~~
/cc @dadap @3XX0 - anyone know of a more elegant fix?
> Fix nginx redirection to ports other than 80

- digits/frameworks/caffe_framework.py
- digits/frameworks/framework.py
- digits/frameworks/torch_framework.py
- digits/model/images/classification/views.py
- digits/model/images/generic/views.py
Current behaviour:
When a classification model is being re-trained the last `InnerProduct` layer is renamed to allow training on another dataset (with a possibly different number of classes).
This implies that the weights of that last layer are discarded.
Problem:
If the model is being re-trained on the same dataset then initially the model will perform badly as it needs to re-learn the weights of its last `InnerProduct` layer.
Solution:
Refrain from renaming the last `InnerProduct` layer if the model is being re-trained on the same dataset
Note:
This applies to Caffe only.
closes #533
> Re-use all weights when re-training on same dataset

- docs/BuildTorch.md
@gheinrich is there any reason why we can't install the `nccl.torch` luarocks package with a single command like we do for other packages?
> Install torch.nccl luarocks pkg w/ single command

- .travis.yml
- scripts/travis/install-caffe.sh
Still takes some work on the Caffe side of things, but this makes it a bit easier to simulate the Travis environment on a non-Travis build system.
> Use Travis scripts outside of Travis more easily

- digits/scheduler.py
I introduced an obscure bug in https://github.com/NVIDIA/DIGITS/pull/465. If you somehow created a pickle file without a job_id, then the `load_past_jobs()` function failed to catch the error (or rather, only caught it the first time), and the server failed to start. This should fix that.
/cc @jmancewicz
> Fix error-handling on loading jobs with no job_id

- examples/regression/README.md
Check if `inputShape` field of external parameters is not nil before calculating dimension of input tensor.
Set dimension to `1` by default for network visualization.
> Make Torch regression example more robust

- examples/regression/README.md
Check if `inputShape` field of external parameters is not nil before calculating dimension of input tensor.
Set dimension to `1` by default for network visualization.
Cherry-pick of #552
> Make Torch regression example more robust (digits-3.0)

- docs/WebInstall.md
Current link is to `docs/docs/UbuntuInstall.md`.  The `docs`  is duplicated.
> Fix broken link to UbuntuInstall.md

- examples/classification/example.py
- examples/classification/use_archive.py
This lets you classify multiple images without needing to edit the example at all. I found it useful while investigating https://github.com/NVIDIA/DIGITS/issues/536.
* Allow multiple input image files
* Expose batch_size as an option
> Improvements to examples/classification/

- docs/BuildTorchLMDB.md
- scripts/travis/install-torch.sh
This reverts commit 3afb6ab5017a234a02e47629a27a8bacddded3f7 (from https://github.com/NVIDIA/DIGITS/pull/545).
See discussion at https://github.com/NVIDIA/DIGITS/issues/544.
> Revert "Use last version of lightningmdb wrapper for Torch"

- tools/torch/data.lua
This is just about removing redundant variable `v` in lua code.
> Fix unmatched local variable initialization.

- digits/frameworks/caffe_framework.py
- digits/frameworks/framework.py
- digits/frameworks/torch_framework.py
- digits/model/forms.py
- digits/model/tasks/caffe_train.py
- digits/model/tasks/torch_train.py
- digits/templates/models/images/classification/new.html
- digits/templates/models/images/generic/new.html
*Close #555*
Disable solvers which aren't supported by the selected framework.
@gheinrich Torch can only do SGD for now, correct?
> Add RMSprop, AdaDelta and Adam solvers

- digits/templates/models/images/classification/custom_network_explanation.html
`<ul>` tag should be outside of `<p>` tag. This PR fixes
`classification/custom_network_explanation.html`. The result is
consistent with `generic/customer_network_explanation.html` and others.
> Fix an ill-formed html file consistently with other html files.

- digits/config/config_file.py
- digits/config/edit.py
- digits/config/load.py
Keep using `digits/digits.cfg` but don't look at `$HOME/.digits.cfg` or `/etc/digits.cfg`.
**Why**
It's not that useful after all and creates too many opportunities for confusing configuration errors.
**How**
This is the quickest way to make the change. It ends up leaving a bunch of cruft in the `digits/config/*` code to handle multiple config files. That could be addressed later.
> Only look in one location for config files

- digits/model/tasks/caffe_train.py
- digits/model/tasks/test_caffe_sanity_checks.py
This should help address the case when a layer is added to manipulate e.g. the label blob. In that case the layer must include a directive like:
include {
phase: TRAIN
}
Otherwise Caffe will drop an error during inference.
A sanity check is added to DIGITS to catch these errors earlier in the process (i.e. before training).
> Drop error if a Caffe layer references an invalid bottom

- examples/classification/example.py
- examples/classification/use_archive.py
Previously, the scripts printed out a misleading message:
```
Processed 1/1 images ...
Classification took 0.0561039447784 seconds.
```
In fact, that value included more computation than just the `net.forward()` call.
Now, you get much more accurate timing information. You can see the difference between the first batch and any subsequent batch, for example:
```
Processed 1/1 images in 0.031234 seconds ...
Processed 1/1 images in 0.006955 seconds ...
Processed 1/1 images in 0.006529 seconds ...
```
Thanks for @flx42 for pointing this out!
> Fix timing in example/classification scripts

- examples/classification/example.py
batch-size argument from command line wasn't being passed to classify(). This resulted in batch-size to always be 1 thereby reducing performance while classifying multiple images (wildcard input)
> pass batch_size to classify() via command line

- digits/job.py
- digits/task.py
- digits/templates/datasets/images/classification/show.html
- digits/templates/datasets/images/generic/show.html
- digits/templates/helper.html
- digits/templates/models/images/classification/show.html
- digits/templates/models/images/generic/show.html
Bug reported at https://groups.google.com/d/msg/digits-users/MW_kHbOEqNo/y7wXpvlSFAAJ
To reproduce:
* Create a dataset from textfiles on the server (i.e. enter the path on the server manually)
* Click on the textfile from the DatasetJob page
* Get a 404 error because the path is wrong
> Fix file serving for files with absolute paths

- digits/frameworks/errors.py
- digits/frameworks/framework.py
- digits/inference/__init__.py
- digits/inference/errors.py
- digits/inference/images/__init__.py
- digits/inference/images/job.py
- digits/inference/job.py
- digits/inference/tasks/__init__.py
- digits/inference/tasks/inference.py
- digits/job.py
- digits/model/images/classification/views.py
- digits/model/images/generic/views.py
- digits/model/tasks/caffe_train.py
- digits/model/tasks/torch_train.py
- digits/model/tasks/train.py
- digits/scheduler.py
- digits/task.py
- digits/templates/job.html
- digits/templates/models/images/classification/classify_many.html
- digits/templates/models/images/classification/classify_one.html
- digits/templates/models/images/classification/top_n.html
- digits/templates/models/images/generic/infer_many.html
- digits/templates/models/images/generic/infer_one.html
- digits/utils/auth.py
- tools/inference.py
Move inference to separate job
* Allow inference to run on different machine within cluster
* Allow long inference jobs to report progress through socketio
* Allow inference to reserve resources (GPUs)
* Image resizing done outside of server context
* Provide command-line inferface for inference using *exactly* the same path as DIGITS
No new feature, will implement socketio updates in separate pull request
* New job and task created for inference
* To limit changes in source code, re-use existing inference API from model job/task
* No code duplication between Caffe/Torch, Classification/Generic
* New inference.py tool performs image resizing and inference
* Results are communicated back to DIGITS through a HDF5 file on filesystem
> Inference jobs

- docs/BuildDigits.md
The package is actually lowercase: http://packages.ubuntu.com/trusty/python-flask
Ubuntu 14.04 doesn't mind the sloppy capitalization, but 16.04 does.
> Fix capitalization of python-flask package in docs

- digits/model/images/classification/views.py
- digits/model/images/generic/views.py
- digits/templates/models/images/classification/show.html
- digits/templates/models/images/generic/show.html
As requested, now the "Classify Many" and "Test Many" tools can use the image limit value.
* Use `num_test_images` for "Classify Many"
* Add `num_test_images` to generic path for "Test Many"
* Default to "All" instead of 100
* Remove a print debugging statement
---
> Use image limit value for "Classify/Test Many"

- digits/inference/tasks/inference.py
- digits/model/images/classification/views.py
- digits/model/images/generic/views.py
- tools/inference.py
Bug introduced by #573: if a path from the list is invalid this leads to a misalignment between image paths and predictions, like:
To fix this the image paths of images that were successfully loaded must be returned by the inference tool.
> Fix inference image paths in presence of invalid paths

- digits/model/tasks/caffe_train.py
*Fix #599*
Fix a few problems:
1. Shallow copying - `infer_many` results are wrong for some images
* Classification - https://github.com/NVIDIA/DIGITS/pull/361 snuck back in with https://github.com/NVIDIA/DIGITS/pull/573
* Generic - has been wrong all along ([see here](https://github.com/NVIDIA/DIGITS/blob/f42f473710/digits/model/tasks/caffe_train.py#L1241))
2. ~~Output ordering - the wrong network output is displayed (e.g. for GoogLeNet)~~
* ~~With https://github.com/NVIDIA/DIGITS/pull/573, network output order is lost and the wrong values are displayed~~
@gheinrich can you verify?
> Deep copy in infer_many

- digits/scheduler.py
On my workstation this reduces the time to execute the following command to 29s down from 36s.
```
./digits-test digits/model/images/classification/test_views.py:TestCaffeCreated
```
Waiting to see the effect on Travis...
> Reduce scheduler polling period in test mode

- digits/templates/models/images/classification/classify_many.html
- digits/templates/models/images/generic/infer_many.html
This mostly helpful when debugging shallow copy errors because it's easy to see when the first 16 images are wrong and everything else is right, for example. Hopefully with #603 those issues will go away and never come back, but this seems like it could still be useful.
Here's a screenshot of this feature used in conjunction with #608 (adds numbering to the bottom table):
> Show image index for infer_many

- digits/inference/tasks/inference.py
- digits/model/images/classification/views.py
- digits/model/images/generic/views.py
- digits/templates/models/images/classification/classify_many.html
- tools/inference.py
Show some stats when ground truth is provided in text file:
- top-1 accuracy,
- top-5 accuracy,
- per-class accuracy,
- confusion matrix.
This may produce output like:
>  	Show accuracy and confusion matrix in classify_many

- digits/model/images/classification/test_views.py
- digits/model/images/generic/test_views.py
- digits/model/tasks/caffe_train.py
- digits/standard-networks/caffe/alexnet.prototxt
- digits/standard-networks/caffe/googlenet.prototxt
- digits/standard-networks/caffe/lenet.prototxt
- digits/templates/models/images/classification/custom_network_explanation.html
- digits/templates/models/images/generic/custom_network_explanation.html
*Close #605, close #623, close #335*
* Use layer.include.stage to specify train/val/deploy all in a single .prototxt description
* Stop automatically creating Softmax layers in deploy networks for classification jobs
* Only set inner_product_param.num_output for classification jobs if it was unset
* Update the standard networks
TODO:
> Use layer stages for all-in-one nets

- requirements.txt
Reported by @flx42
If you have `wtforms==1.0.1` installed from the [ubuntu deb package](http://packages.ubuntu.com/trusty/python/python-wtforms) `python-wtforms`, and then run `pip install -r requirements.txt`, you would expect pip to install `wtforms>=1.0.5` since `requirements.txt` includes the line `Flask-WTF>=0.11` and `Flask-WTF==0.11` requires `wtforms>=1.0.5` ([see here](https://github.com/lepture/flask-wtf/blob/v0.11/setup.py#L51)).
But it doesn't. So we have to specify the requirement again.
> Force requirement wtforms>=2.0.0

- tools/torch/test.lua
That statement is redundant with a previous statement.
Besides, that statement fails when test.lua is called from its own directory.
close #641
> Remove unnecessary statement in test.lua

- digits/model/tasks/train.py
Fixes two errors when you have missing graph data:
1. `TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'`
2. `Uncaught ReferenceError: None is not defined`
> Handle missing graph data gracefully

- digits/model/forms.py
- digits/model/tasks/train.py
- digits/templates/models/images/classification/new.html
- digits/templates/models/images/generic/new.html
- digits/templates/models/python_layer_explanation.html
*Close #636*
Cleanup Python layer upload UI and add some pop-out text similar to https://github.com/NVIDIA/DIGITS/pull/628#issuecomment-195137527.
Also add network outputs with names containing "accuracy" to the accuracy axis in graphs. It's a little hacky, but I don't think we need to find a general purpose solution to that problem just yet.
> Add pop-out explanation for Python layers

- tools/torch/main.lua
Fix type of Lua wrapper for Torch. Validation batch size is coming in a field named `validationBatchSize` as mentioned on the [doc](https://github.com/NVIDIA/DIGITS/blob/v3.2.0/docs/GettingStartedTorch.md#internal-parameters).
> Fix Torch validation batch size import from net desc

- digits/device_query.py
- digits/model/forms.py
**Versioned DSOs**
We really shouldn't ever load unversioned DSOs because you shouldn't need dev files to run any application. I ran into this issue when using `nvidia-docker`, which doesn't include `libnvidia-ml.so` by default.
**Displaying GPU memory**
We could just display CUDA info only - there's no clear reason to call NVML here - but I have a vague recollection of CUDA being unable to query the memory available for newer, fancier GPUs sometimes. So I'm just adding it as a fallback path.
I can't test this on Windows, but I've attempted to preserve @crohkohl's changes from #199.
> Device query updates

- digits/model/images/classification/views.py
- digits/model/images/generic/views.py
- digits/templates/models/images/classification/show.html
- digits/templates/models/images/generic/show.html
Before this PR, you could manually enter a path to an image on the server for testing, but the image would be deleted afterwards!
Now you get autocomplete help for entering paths, and the image won't be deleted afterwards.
> Allow autocomplete for testing image paths

- digits/inference/tasks/inference.py
- digits/model/images/generic/test_views.py
- digits/model/images/generic/views.py
- digits/templates/models/images/generic/infer_db.html
- digits/templates/models/images/generic/show.html
- tools/inference.py
A (small) step towards support for non-image data: this makes it possible to perform inference on any 3D blob. Blobs may not be "proper" images (e.g. because they don't have a standard number of channels).
close #619
close #630 
A new field and a new button were added to allow inference on LMDB database:
Results are shown as follows (using DB key instead of image path):
> Support for inference on LMDB

- digits/model/tasks/torch_train.py
This is required for applications where input data must be exact.
> Use lossless image type during Torch inference

- docs/BuildTorch.md
- scripts/travis/install-torch.sh
- tools/torch/data.lua
Luajit heap size must be located in the lower 2GB of addressable memory.
There is therefore a limit of 2GB on heap size when using Luajit.
This change moves LMDB keys to a tds.Vec object, where memory does not rely on the Lua allocator.
close #659
> Allocate LMDB keys in tcs.Vec object

- digits/model/images/classification/test_views.py
- digits/model/images/classification/views.py
Since #628 DIGITS does not overwrite the number of outputs in the last fully-connected layer if it is already set to a value.
If the user accidentally specifies too large a `num_output` then inference will fail as reported on #678.
This change causes classification outputs to be ignored if there is no corresponding label.
close #678
> Ignore classification outputs without corresponding label

- tools/download_data/cifar100.py
Before:
```
/home/lyeager/cifar100/coarse/test/vehicles_2:
total 0
lrwxrwxrwx 1 lyeager lyeager 43 Apr 18 17:22 lawn_mower -> /home/lyeager/cifar100/fine/test/lawn_mower
lrwxrwxrwx 1 lyeager lyeager 39 Apr 18 17:22 rocket -> /home/lyeager/cifar100/fine/test/rocket
lrwxrwxrwx 1 lyeager lyeager 42 Apr 18 17:22 streetcar -> /home/lyeager/cifar100/fine/test/streetcar
lrwxrwxrwx 1 lyeager lyeager 37 Apr 18 17:22 tank -> /home/lyeager/cifar100/fine/test/tank
lrwxrwxrwx 1 lyeager lyeager 40 Apr 18 17:22 tractor -> /home/lyeager/cifar100/fine/test/tractor
```
After:
```
/home/lyeager/cifar100/coarse/test/vehicles_2:
total 0
lrwxrwxrwx 1 lyeager lyeager 29 Apr 18 17:20 lawn_mower -> ../../../fine/test/lawn_mower
lrwxrwxrwx 1 lyeager lyeager 25 Apr 18 17:20 rocket -> ../../../fine/test/rocket …
```
> Use relative symlinks in Cifar100 download tool

- examples/fine-tuning/lenet-fine-tune.prototxt
The softmax layer in the fine-tine example for Caffe was pointing to the `ip2` bottom.
It should point to `ip2_odd_even` instead.
close #689
> Fix fine-tune example softmax bottom

- digits/templates/datasets/images/classification/new.html
- digits/templates/datasets/images/classification/show.html
The dataset creation form does not explicitly state which of the image dimension fields is the width and which is the height.
Though this can be inferred through `See example` it would probably help to make this explicit.
See #693
> Image dimension hint

- docs/BuildTorch.md
- scripts/travis/install-torch.sh
`sys` and `image` modules are automatically installed as part of the default Torch7 install.
> Remove unnecessary installs

- tools/torch/data.lua
Errors in Torch threads are propagated to the main thread since https://github.com/torch/threads/commit/a9d4eca0ebb412a886cdc736a6e92a16851211a9. For those using older versions this commit moves the error checking in DIGITS data loader threads to after `dojob()`.
Also fix log message that shows image width/height.
> Improve error reporting from Torch threads

- digits/config/caffe_option.py
- digits/model/tasks/caffe_train.py
Loading h5py before caffe to solve hdf5 dll issue.
Casting histogram to float32 to ensure correct format in JSON.
> Minor modification to support DIGITS for Windows

- digits/templates/models/images/classification/new.html
- digits/templates/models/images/generic/new.html
This selector, although missing a closing bracket, works in chrome and firefox, but not in safari. Seemed like a good thing to fix just in case browsers become more picky in the future.
> fix bug in solver_type selector

- digits/model/forms.py
- digits/model/images/classification/test_views.py
- digits/model/images/classification/views.py
- digits/model/images/generic/test_views.py
- digits/model/images/generic/views.py
- digits/model/views.py
- digits/templates/models/images/classification/new.html
- digits/templates/models/images/generic/new.html
- digits/utils/forms.py
Adding the ability to sweep Batch Size and Learning Rate.  Their entry fields now accept multiple values.
Each permutation of the swept fields will generate one job. With Batch Size [1,2] and Learning Rate [0.01, 0.015, 0.02], six jobs will be created.  The job names are augmented by the swept field value.  When multiple jobs are launched, the page is redirected to the home page rather than a job page.
If you were to clone one of these jobs, it will only have the values of that particular job. The clone data is saved per job.
> Add parameter sweep to learning rate and batch size

- digits/inference/job.py
- digits/job.py
- digits/scheduler.py
~~Volatile jobs are not persisted to disk. Besides, they are automatically deleted by the scheduler 1 hour after completion.~~
These jobs are not saved to disk. Besides, they are automatically deleted by the scheduler 1 hour after completion.
This should become useful if jobs are increasingly used for background processing, inference, etc.
> Support for non-persistent jobs

- digits/dataset/images/classification/job.py
- digits/dataset/images/generic/job.py
- digits/dataset/job.py
- digits/model/images/classification/job.py
- digits/model/images/classification/views.py
- digits/model/images/generic/views.py
- digits/model/tasks/caffe_train.py
- digits/model/tasks/torch_train.py
- digits/model/tasks/train.py
- digits/templates/datasets/images/classification/show.html
- digits/templates/datasets/images/classification/summary.html
- digits/templates/datasets/images/generic/summary.html
- digits/templates/home.html
- tools/inference.py
This will allow to create new types of datasets without making changes in other parts of DIGITS.
Ultimately, class relationships may look like:
> Expose common dataset interface

- digits/standard-networks/caffe/alexnet.prototxt
- digits/standard-networks/caffe/googlenet.prototxt
- digits/standard-networks/caffe/lenet.prototxt
This pull request makes 3 updates to the Caffe standard networks:
1. Give unique names to the `train`/`val` `Data` layers in each network, and use stage for include rules instead of phase
1. Change LeNet to use the `Data` layer for input scaling during `train`/`val`, but still use a `Power` layer during `deploy`.
1. Update the batch sizes
* All are now powers of two
* AlexNet and GoogLeNet use the training batch sizes that were used in their original papers
The first change is purely cosmetic. The second may have a slight but negligible improvement in performance. I made the third change because cuDNN typically prefers batch sizes that are even powers of two.
> Update standard networks for Caffe

- digits/static/js/table_selection.js
Fix selection bug mentioned in #741 where if drag selection finishes with a mouse up outside of the table, that it gets stuck in a mouse down mode.
> Fix selection bug mentioned in #741

- digits/static/js/table_selection.js
Changing the behavior to deselect the table rows if the mouse is clicked outside of the table with the exception of `input`, `textarea`, `button`, and `a`
> Deselect with click outside the tables

- digits/utils/forms.py
When a job is cloned and a newer form has been added to the job creation page, DIGITS warns that the new form element was not cloned.  This is unnecessary and distracting.  Removing.
> remove warning when cloning with new form elements

- digits/job.py
- digits/task.py
- digits/templates/job_row.html
- digits/views.py
*Close #706, close #729*
*Fix #709, replace #739*
@pansk @TimZaman @jmancewicz @mpbrigham - Thanks for the bug reports and proposed fixes!
Is everyone happy with this solution? Check the docstring for how `runtime_of_tasks()` is calculated:
```py
def runtime_of_tasks(self):
"""
Returns the time (in sec) between when the first task started and when the last task stopped
NOTE: this may not be what you're expecting if there was some WAIT time in-between
"""
```
> Calculate status and runtime for job from tasks

- digits/templates/home.html
- digits/templates/job_management.html
The tables on the front page were shifted to the right from being in a container.
> A few small layout changes

- digits/static/js/table_selection.js
- digits/templates/home.html
Changed the parenthetical job counts on the front pages to represent the filtered list.
ctrl-click had been opening a new tab AND redirecting the current page. Removed code that is no longer needed for selection.
> Fixed ctrl-click and job count

- digits/standard-networks/torch/ImageNet-Training/alexnet.lua
- digits/standard-networks/torch/ImageNet-Training/googlenet.lua
- digits/standard-networks/torch/lenet.lua
- tools/torch/main.lua
- tools/torch/test.lua
Datapoints:
MNIST+LeNet (30 epochs)
1 GPU: 56s
2 GPUs: 2m51s
(not unexpected due to communication overhead)
Upscaled CIFAR + Alexnet (10 epochs):
1 GPU: 13m11s
2 GPUs: 13m7s
Upscaled CIFAR + Googlenet (2 epochs):
1 GPU: 16m20s
2 GPUs: 11m13s
> New Torch multi-GPU programming model

- digits/static/js/home_app.js
- digits/static/js/jquery.time_filters.js
- digits/templates/home.html
Adding tooltips to the job name in case the overrun and ellipsis appear as well as to the elapsed and submitted times to get a little more information. If the elapsed time is 4m, the tooltip will unpack that a bit to 3 minutes, 43 seconds or 4 minutes, 13 seconds.  To that end, the time functions are changing from flooring to rounding of the least significant value.
> Add tooltips and round the time values

- digits/standard-networks/torch/ImageNet-Training/alexnet.lua
- digits/standard-networks/torch/ImageNet-Training/googlenet.lua
- digits/standard-networks/torch/lenet.lua
Make them match Caffe's from https://github.com/NVIDIA/DIGITS/pull/733.
I tested them all on a GTX 980 (4GB card) and none ran out of memory.
> Update batch sizes for standard torch networks

- digits/static/js/home_app.js
- digits/templates/home.html
This is an option for dealing with the length of job names on the front page. The Datasets and Models are in tabs. One upside of not putting them in tabs is the potential to show to dependencies between models and datasets.
> Move Datasets and Models into tab view

- digits/views.py
DIGITS fails to display a meaningful error when the user is attempting to delete a dataset that has references.
> Fix display of errors when deleting jobs

- digits/config/caffe_option.py
- digits/templates/layout.html
- digits/webapp.py
Try to retrieve caffe version from command line option '-version' and if caffe.exe is not built with such information, fallback to default (0,11,0).
> Retrieve caffe version from caffe.exe.

- digits/dataset/generic/views.py
- digits/dataset/images/classification/views.py
- digits/dataset/images/generic/views.py
- digits/dataset/views.py
- digits/model/images/classification/views.py
- digits/model/images/generic/views.py
- digits/model/views.py
- digits/scheduler.py
- digits/templates/job.html
See #667 , revised version of #668.
See below for screenshots. Very straightforward.
Ready for review @lukeyeager (https://github.com/NVIDIA/DIGITS/issues/667#issuecomment-220705017)
> Related Jobs in Dataset and Model view

- tools/create_generic_db.py
Encoded Datum objects can have the data shape specified through `width`, `height` and `channels` fields.
DIGITS wrappers for Torch relies on this to determine the shape of the input data.
The `channels` field was previously left uninitialized.
This change fixes this.
> Fix channels in encoded Datum

- digits/extensions/view/__init__.py
- digits/extensions/view/interface.py
- digits/extensions/view/rawData/__init__.py
- digits/extensions/view/rawData/config_template.html
- digits/extensions/view/rawData/forms.py
- digits/extensions/view/rawData/view.py
- digits/extensions/view/rawData/view_template.html
- digits/model/images/generic/test_views.py
- digits/model/images/generic/views.py
- digits/model/views.py
- digits/templates/models/images/generic/infer_db.html
- digits/templates/models/images/generic/infer_many.html
- digits/templates/models/images/generic/infer_one.html
- digits/templates/models/images/generic/show.html
This implements a visualization framework along the lines of:
Depends on #731 
A `rawData` view extension is added and selected by default to show the network output in the same way as in the original generic type of networks.
> View extension framework

- digits/extensions/data/__init__.py
- digits/extensions/data/objectDetection/__init__.py
- digits/extensions/data/objectDetection/data.py
- digits/extensions/data/objectDetection/forms.py
- digits/extensions/data/objectDetection/template.html
- digits/extensions/data/objectDetection/utils.py
- digits/extensions/view/__init__.py
- digits/extensions/view/boundingBox/__init__.py
- digits/extensions/view/boundingBox/config_template.html
- digits/extensions/view/boundingBox/forms.py
- digits/extensions/view/boundingBox/summary_template.html
- digits/extensions/view/boundingBox/view.py
- digits/extensions/view/boundingBox/view_template.html
- digits/extensions/view/interface.py
- digits/extensions/view/rawData/__init__.py
- digits/extensions/view/rawData/config_template.html
- digits/extensions/view/rawData/forms.py
- digits/extensions/view/rawData/view.py
- digits/extensions/view/rawData/view_template.html
- digits/model/images/generic/test_views.py
- digits/model/images/generic/views.py
- digits/model/views.py
- digits/templates/models/images/generic/infer_db.html
- digits/templates/models/images/generic/infer_many.html
- digits/templates/models/images/generic/infer_one.html
- digits/templates/models/images/generic/show.html
- digits/utils/image.py
- digits/utils/test_image.py
Planning to split this into small pull requests. This is the complete object detection work flow.
This includes frameworks for data and view extensions.
The object detection data extension creates datasets from object detection datasets. On the main page, select `New dataset > Images > Object Detection`
The dataset is configured with a form:
To create the model: on the main page, select `New Model > Images > Object Detection`.
After the model is trained, on the model page, select the bounding box view extension:
Then proceed to inference as usual. If you do `Test Many`, you may see something like:
~~This includes as a bonus:~~
~~- an image gradient work flow (the data extension creates datasets as in the image regression example) and the view extension displays arrows that point to the …
> Object detection workflow

- .travis.yml
- scripts/travis/install-caffe.sh
- scripts/travis/install-torch-wrapper.sh
- scripts/travis/install-torch.sh
By removing the build time entirely, this brings the total TravisCI build+test time down from ~20 minutes to ~12 minutes when a cached build is present.
> Cache Caffe and Torch builds in Travis for 1 week

- digits/model/images/generic/views.py
`summary_html` may be used unitialized if an error occurs during inference.
> Fix use of uninitialized summary_html

- digits/model/images/generic/job.py
The common dataset interface exposes a get_mean_file() method to retrieve the mean file.
Using the dataset.mean_file attribute only works for "images/generic" datasets.
This should have been changed in #723
> Fix use of non-common dataset interface in generic models

- digits/model/tasks/torch_train.py
- tools/torch/test.lua
The resize mode is no longer used by the Torch wrapper in `test.lua`.
Besides, this field isn't part of the common dataset interface.
Using it is causing problems during multiple image inference in Torch when using generic datasets.
This should have been changed in #723
> Remove unused resize_mode in Torch path

- digits/model/tasks/caffe_train.py
- digits/task.py
When Python layer is included in network, an exception occurred in caffe.exe (see [this](https://github.com/Microsoft/caffe/issues/87), related to LayerParamter having no to_python converter.  However, both pycaffe in Windows, and caffe/pycaffe in Linux worked without issue.  This workaround tries to run pycaffe in Windows when both of the following conditions meet.
1.  At least one layer in the network has Type == 'Python'
2.  platform.system() is 'Windows'
In other conditions, the usual caffe.exe will be used.
> Workaround for python layer in Windows

- digits/config/caffe_option.py
- digits/frameworks/caffe_framework.py
- digits/model/tasks/caffe_train.py
- digits/templates/layout.html
- digits/utils/errors.py
- digits/webapp.py
1. parse_version may return ('00000001','*','00000003','*final'), which is hard to to convert back to '1.0.0-rc3.'  Therefore, storing the original version string as a backup for Info menu.
2. Flavor will be NVIDIA if libcaffe.so is built with NVIDIA enhancement (Linux only).  In other cases, flavor is BVLC.
3. Store information in CaffeOption class so no need to query caffe for linked libraries twice.
> Allow BVLC/caffe and caffe-on-windows

- digits/extensions/data/objectDetection/utils.py
Before:
NameError: global name 'exception' is not defined
After:
RuntimeError: error: no label files found in /raid/images/kitti/dlar-split2/train/image_2
> Fix Exception in extensions.data.objDetection.util

- digits/templates/datasets/generic/show.html
Show only those tasks that are not 'D' (done without error) and those that have more than zero entries.
> Don't show create_generic_db dummy tasks

- .travis.yml
- scripts/travis/install-apt.sh
- scripts/travis/install-caffe.sh
*Enabled by https://github.com/NVIDIA/DIGITS/pull/769*
It'll be nice to know when/if they break something that DIGITS expects from a Caffe build.
I believe TravisCI will store separate caches for each Caffe build.
> Test BVLC/caffe as well as NVIDIA/caffe on Travis

- tools/create_generic_db.py
We shouldn't change the RGB channel order to BGR when using encoded images.
> Fix encoded image channel order

- requirements.txt
Otherwise, you get a cryptic error:
```
exc_class = default_exceptions[exc_class_or_code]
KeyError: 300
```
> Fix Flask requirement to 0.10.1

- digits/model/tasks/caffe_train.py
The solver_mode value in solver.prototxt seems not parsed in pycaffe.  Hence, even that parameter is set to GPU and we also call set_device to one of available GPU's, pycaffe still uses CPU for most of its computation.
To avoid that, in addition to set_device, caffe.set_mode_gpu() has to be called explicitly right after set_device() to enable GPU mode.
Additionally, using sys.executable instead 'python' to make the arguments more portable.
> Set GPU mode explicitly

- digits/templates/home.html
The wells containing the Models and Datasets tables were not strictly in the container div so that as the window width was decreased, the wells could creep off screen before the divs were resized.
> Fix the table to fit in the container

- digits/static/js/home_app.js
- digits/templates/home.html
When sorting with two columns (click on a column header and shift-click a second) the blank entries in the second column could be at the top or the bottom of that column depending on the ascending / descending state.
I've replaced the predicte functions and empty_to_the_end filter with a custom sort filter.
> Double sort with blanks fix

- digits/dataset/generic/test_views.py
- digits/dataset/generic/views.py
- digits/dataset/images/classification/views.py
- digits/dataset/tasks/create_generic_db.py
- digits/templates/datasets/generic/show.html
- digits/templates/datasets/images/explore.html
- digits/utils/lmdbreader.py
- tools/inference.py
Add button to explore **encoded** LMDBs
> Explore generic datasets

- digits/model/forms.py
- digits/model/tasks/caffe_train.py
- digits/model/tasks/torch_train.py
Close https://github.com/NVIDIA/DIGITS/issues/849.
See explanation at https://github.com/NVIDIA/DIGITS/pull/498#issuecomment-226550671.
> Fixes for multiple pretrained model files

- digits/model/tasks/caffe_train.py
We have to loop over each pre-trained weight file when loading those files.
This fix depends on PR#851.  I will rebase this after PR#851 is merged.
> Fix loading multi weight files in _pycaffe_args

- digits/static/js/home_app.js
- digits/templates/home.html
When the Model and Dataset table widths were corrected, the Running Jobs table was not. This makes similar changes to the Running Jobs.
> fix table width and reformat the filter and buttons

- digits/static/js/home_app.js
*Close #853*
The sorting function is fixed. It needed to return -1, 0, -1, but had been returning true, false. The Boolean return appeared to work in FireFox, but that may have been a coincidence.
Also changed the default descending choice when a column is first selected based on whether the columns data type is a string on not. This has strings sort a->z and numbers and dates (large -> small). This is similar to OSX file browser. This gives the "logical" choice and feels natural.
> Fixed the sorting function.

- docs/StandardDatasets.md
Since in the GSG we use `~/mnist`.
Note: the paths are arbitrary - you can use whatever you like.
> Standardize paths for standard datasets in docs

- digits/extensions/data/objectDetection/README.md
- digits/extensions/data/objectDetection/data.py
- digits/extensions/data/objectDetection/forms.py
- digits/extensions/data/objectDetection/template.html
- digits/extensions/data/objectDetection/utils.py
- digits/utils/forms.py
This change makes it optional to pad images when creating an object detection dataset.
A form validator is added to verify that either both or none of width/height are specified when validating the form.
Doing this in the form validator instead of (like formerly) the extension instantiation helps drop a more user-friendly error.
Template updated to show width/height on same row.
> Make padding optional in object detection data extension

- docs/BuildDigitsWindows.md
In Windows environment, document originally points to old dependency (cudnn 4).  Update it to recommend using the latest library (cudnn 5.1).
> Update doc to point to cudnn 5.1

- digits/device_query.py
Needed for compatibility with upcoming CUDA 8.0 release.
> Make device_query robust to future toolkits

- examples/object-detection/prepare_kitti_data.py
The script seems to assume that files from `devkit_object.zip` will be uncompressed into a folder `devkit` however that is not the case when using the archive from KITTI (?).
> Fix path to kitti devkit in data preparation script

- digits/model/images/classification/job.py
- digits/model/images/classification/test_views.py
- digits/model/images/generic/job.py
- digits/model/images/generic/test_views.py
- digits/model/images/job.py
- digits/model/tasks/caffe_train.py
- digits/model/tasks/torch_train.py
- digits/model/tasks/train.py
- digits/model/views.py
> Get stats & original network def from "Download Model" button

- docs/BuildCaffe.md
NVcaffe added a dependency on the Python bindings for OpenCV with https://github.com/NVIDIA/caffe/pull/144. Unfortunately, there doesn't seem to be a PyPI package for OpenCV, so we can't fix this just by updating `$CAFFE_HOME/python/requirements.txt`.
> Update documentation to add python-opencv package

- digits/dataset/images/generic/test_lmdb_creator.py
- examples/siamese/create_db.py
- examples/text-classification/create_dataset.py
- tools/create_db.py
- tools/create_generic_db.py
There's really no need for these
> Remove unnecessary print messages for LMDB mapsize

- digits/templates/error.html
- digits/templates/home.html
- digits/templates/layout.html
- digits/templates/models/images/classification/classify_one.html
- digits/templates/models/images/classification/large_graph.html
- digits/templates/models/images/classification/show.html
- digits/templates/models/images/generic/infer_one.html
- digits/templates/models/images/generic/large_graph.html
- digits/templates/models/images/generic/show.html
- digits/utils/filesystem.py
- digits/webapp.py
When moving between versions of DIGITS changes in javascript content can cause render issues.
git checkout 74afccb
reload the DIGITS home page, click on a job name to navigate to a job page,
git checkout d0b407a
Use the DIGITS link in the upper left corner to navigate back to the home page.
The content of the app javascript file has changed, however the file is cached in session by the name, and the name has not changed. To flush the cache a hash for the static directory is being added to the url for the .js and .css files.
> Add a hash to cached assets (.js and .css files)

- digits/extensions/data/objectDetection/README.md
Currently, that's the only type of identifier that's supported.
In the `digits-4.0` branch, we'll just change the documentation so as to not make any unnecessary functional changes before the public release. On the `master` branch, we should enable non-numerical identifiers.
> ObjectDetection docs - use numerical identifiers

- .travis.yml
It refers to the caching command timeout (https://github.com/travis-ci/travis-ci/issues/6317#issuecomment-233065994), not how long before the caches expire as I had thought.
> Stop setting cache timeout in TravisCI

- digits/model/tasks/caffe_train.py
*Caused by #307*
Convert from NetParameter to string back to NetParameter to avoid this error:
> TypeError: Parameter to MergeFrom() must be instance of same class:
expected caffe_pb2.NetParameter got caffe.proto.caffe_pb2.NetParameter.
/cc @ajtao
> Upgrade caffe_train_task.network object type

- digits/frameworks/caffe_framework.py
- digits/frameworks/torch_framework.py
- digits/model/images/classification/test_views.py
- digits/model/images/classification/views.py
- digits/model/images/forms.py
- digits/model/images/generic/views.py
- digits/model/tasks/torch_train.py
- digits/model/tasks/train.py
- digits/static/css/style.css
- digits/templates/models/data_augmentation.html
- digits/templates/models/images/classification/new.html
- digits/templates/models/images/generic/new.html
- tools/torch/data.lua
- tools/torch/main.lua
- tools/torch/test.lua
Data augmentation needs little introduction I recon. It counters overfitting and makes your model generalize better, yielding better validation accuracies; or alternatively, allows you to use smaller datasets with similar performance. 
In the Zoo that's the internet, I see many implementations of different augmentations, of which few are proper and nicely portable. A part from Digits yielding a great UI; ease of use; and deep learning turn-key solution, I strongly feel we can expand to the functional side as well to make this a deep learning killer-app.
For torch, I have made an implementation _during lua preprocessing_ from frontend to backend to enable Digits to do so. In #330 there was already an attempt for augmentation, which happened on the dataset-creation side; something I am …
> Torch Data Augmentation

- tools/test_analyze_db.py
Fixes this issue:
```
$ ./digits-test tools/
E............................................................................................................................
======================================================================
ERROR: Failure: ImportError (No module named caffe.io)
----------------------------------------------------------------------
File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 418, in loadTestsFromName
addr.filename, addr.module)
File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
return self.importFromDir(dir_path, fqname)
File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
mod = load_module(part_fqname, fh, filename, desc)
File …
```
> Make "./digits-test tools/" work again

- digits/dataset/generic/test_views.py
- digits/extensions/data/__init__.py
- digits/extensions/data/imageProcessing/__init__.py
- digits/extensions/data/imageProcessing/data.py
- digits/extensions/data/imageProcessing/forms.py
- digits/extensions/data/imageProcessing/template.html
- digits/extensions/view/__init__.py
- digits/extensions/view/imageOutput/__init__.py
- digits/extensions/view/imageOutput/config_template.html
- digits/extensions/view/imageOutput/forms.py
- digits/extensions/view/imageOutput/view.py
- digits/extensions/view/imageOutput/view_template.html
- digits/model/images/generic/test_views.py
This adds data and view extensions to train image processing networks in DIGITS. This may be used for de-noising, super-resolution, segmentation, etc.
The image processing data extension creates datasets for which both the input and the label are images.
The image view extension displays the network output as an image.
Only works with Caffe for now. Torch wrappers need to be updated to deal with image labels (currently only scalar or vector labels are supported).
> Image processing workflow

- digits/dataset/generic/test_views.py
- digits/extensions/data/__init__.py
- digits/extensions/data/imageProcessing/__init__.py
- digits/extensions/data/imageProcessing/data.py
- digits/extensions/data/imageProcessing/forms.py
- digits/extensions/data/imageProcessing/template.html
- digits/extensions/view/__init__.py
- digits/extensions/view/imageOutput/__init__.py
- digits/extensions/view/imageOutput/config_template.html
- digits/extensions/view/imageOutput/forms.py
- digits/extensions/view/imageOutput/view.py
- digits/extensions/view/imageOutput/view_template.html
- digits/model/images/generic/test_views.py
- tools/torch/data.lua
> Support image labels in Torch

- .travis.yml
- scripts/travis/install-caffe.sh
The default branch for NVcaffe is now 0.15:
https://github.com/NVIDIA/caffe/branches
> Use default branches for TravisCI caffe builds

- docs/BuildTorch.md
- scripts/travis/install-torch.sh
*Close #974*
Cherry-pick of https://github.com/NVIDIA/DIGITS/pull/928 into `digits-4.0` branch.
> [digits-4.0] Explicitly use Lua LMDB wrapper version 0.9.18.1-1

- digits/extensions/view/boundingBox/app_begin_template.html
- digits/extensions/view/boundingBox/app_end_template.html
- digits/extensions/view/boundingBox/config_template.html
- digits/extensions/view/boundingBox/forms.py
- digits/extensions/view/boundingBox/header_template.html
- digits/extensions/view/boundingBox/view.py
- digits/extensions/view/boundingBox/view_template.html
- digits/extensions/view/interface.py
- digits/model/images/generic/views.py
- digits/templates/models/images/generic/infer_db.html
- digits/templates/models/images/generic/infer_many.html
- digits/templates/models/images/generic/infer_one.html
- digits/utils/image.py
- digits/utils/test_image.py
In preparation for the multi-class object detection display, I have moved the drawing of the bounding boxes from the server to the client. This will allow quicker interactions with the display. Users will be able to toggle displays of bounding boxes by class, adjust the image desaturation if there are color conflicts between the image a class's bounding box color, and change the line width.
So that the lines are drawn with a fixed width regardless of scale, the images are redrawn when the window is resized such that the image display is resized.
The header text "Found 7 box(es) in 3 image(s)" has been changed to drop the "in `n` images" if the number of images is one and to pluralize "box" as needed.
The line width and desaturation settings are saved per browser.
> Move bounding box drawing from the server to the client.

- digits/model/tasks/train.py
Bug from https://github.com/NVIDIA/DIGITS/pull/800.
Sometimes when a job fails there may not be a `self.p.pid`:
```
File "/home/lyeager/digits/venv1/local/lib/python2.7/site-packages/gevent/greenlet.py", line 327, in run
result = self._run(*self.args, **self.kwargs)
File "/home/lyeager/digits/digits/model/tasks/train.py", line 194, in hw_socketio_updater
data_cpu['pid'] = self.p.pid
AttributeError: 'NoneType' object has no attribute 'pid'
<Greenlet at 0x7f492632f550: <bound method CaffeTrainTask.hw_socketio_updater of <digits.model.tasks.caffe_train.CaffeTrainTask object at 0x7f4926316190>>(['0'])> failed with AttributeError
```
I think this error is actually harmless as the thread would get killed anyway. But it's no fun seeing messages like that in the …
> Better error-checking in psutil code

- digits/device_query.py
`device_query.py` wasn't able to detect a CUDA device on my macbook.
```shell
$ python digits/device_query.py
No devices found.
```
```shell
python digits/device_query.py
Device #0:
>>> CUDA attributes:
name                         GeForce GT 750M
totalGlobalMem               2147024896
clockRate                    925500
major                        3
minor                        0
```
It seems that this is originally addressed in https://github.com/NVIDIA/DIGITS/commit/56af4ec9ae5a5e5b3616d41096520b89b169eee4, but lost in https://github.com/NVIDIA/DIGITS/commit/e69019d5ac8ae5bbd14c227240db4735e124c70c.
> fix cudart load on osx

- digits/standard-networks/torch/ImageNet-Training/alexnet.lua
- digits/standard-networks/torch/ImageNet-Training/googlenet.lua
- digits/standard-networks/torch/lenet.lua
- docs/GettingStartedTorch.md
- tools/torch/main.lua
This change enables automatic encapsulation in an `nn.DataParallelTable` container for multi-GPU training. This comes from @thatguymike's realization that this would simplify the programming model. A `disableAutoDataParallelism` flag is added to the internal parameters to disable this mechanism. This flag is intended to be used by users who wish to retain control over what exactly gets parallelized. As an example, the standard Alexnet model enables this flag to parallelize only the feature part of the network.
Note: this changes does not enable threading in `nn.DataParallelTable` when doing the automatic encapsulation. Some of the numbers below are showing training time with/without threading.
For the record, some training time numbers:
LeNet:
1 GPU => 1m3s
2 GPUs, all parallel, …
> Rework Torch multi-GPU training

- digits/templates/models/images/classification/show.html
- digits/templates/models/images/generic/show.html
Changing the Browse buttons in the file inputs for Image Testing from
to
I might try to make this into a template or an angularjs directive.
> Make the Browse... buttons more bootstrap styled

- digits/standard-networks/caffe/lenet.prototxt
- digits/standard-networks/torch/lenet.lua
Removed scaling from data layers and kept single unified power layer. Previous definition was faster due to multi-threaded data loader, but potentially less straightforward to new users.
The scaling factor 0.0125 corresponds to 1/(standard deviation on MNIST dataset), which is ~80 per pixel (from a range of [0-255] per pixel). Scaling factor comment updated to reflect this.
> Simplify input scaling on LeNet network

- digits/model/views.py
- digits/pretrained_model/tasks/caffe_upload.py
- digits/pretrained_model/tasks/torch_upload.py
- digits/pretrained_model/tasks/upload_pretrained.py
Change file concat to os path join
> Change file concat to os path join

- docs/BuildDigitsWindows.md
Test DIGITS master branch with new requirements.txt on Windows.  The Pillow package can't be installed via pip due to missing jpeg library.  Users can install Pillow 3.1.1 via Windows installer executable instead.
> Add how to install Pillow in Windows.

- digits/extensions/data/objectDetection/data.py
I was stuck for a long time trying to train my own data when I realized that the reason my object detection model wasn't training was because when I created the database, I used capitalized custom class names like `DontCare,Pedestrian` instead of lower cased names, ie. `dontcare,pedestrian`. I thought that since my labels had capitalized names (like `Pedestrian`) the custom class names could also be capitalized.
In the file `digits/extensions/data/objectDetection/utils.py` the class names are lower cased when read from the label files (line `183` shown below).
``` python
gt.stype = row[0].lower()
```
However, when the custom classes are created from the Object Detection dataset page, they aren't lower cased. I changed a line to make this happen so that the custom classes and the classes …
> Change DataIngestion to lowercase all class names

- digits/utils/time_filters.py
After re-installing a bunch of Python packages I ended up with a combination of packages that couldn't support the unicode characters coming out of [print_date](https://github.com/NVIDIA/DIGITS/blob/v4.0.0/digits/utils/time_filters.py#L6). I got errors like below due to the presence of accents in French for "August".
```
UnicodeDecodeError
'ascii' codec can't decode byte 0xc3 in position 7: ordinal not in range(128)
File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/home/greg/ws/digits/digits/webapp.py", line 69, in decorated
return …
```
> Fix unhandled unicode from date_print

- docs/BuildDigitsWindows.md
Include a paragraph to inform users that DetectNet is not implemented on BVLC Caffe.  As a result, that feature is not available on DIGITS for Windows.
> Update document to include limitation on Windows.

- digits/job.py
I always end up with weird errors because I switch around between PR branches so often. This just adds a little more info to help debug the error messages. Shouldn't affect normal users at all.
> Print a little more info for errors in job.save()

- digits/extensions/data/objectDetection/forms.py
Using validators.InputRequired() instead of validators.DataRequired() as the latter requires the data to be both present and un-falsey.
fix #1030
> Allow min_box_size to be zero in Object Detection extension

- digits/extensions/data/imageSegmentation/data.py
- digits/extensions/data/imageSegmentation/forms.py
- digits/extensions/data/imageSegmentation/template.html
Add form fields to allow users to provide separate text file with color/class mappings.
This is useful when working with datasets that have label images in RGB.
Depends on #961
>  	Allow segmentation color map to be specified explicitly

- digits/static/js/home_app.js
- digits/templates/home.html
- digits/templates/partials/home/datasets_pane.html
- digits/templates/partials/home/model_pane.html
- digits/templates/partials/home/pretrained_model_pane.html
Both the Delete and Abort buttons bring up the confirmation popup when the buttons is disabled.
> Block Delete Jobs popup when no jobs are selected

- digits/__init__.py
- digits/test_version.py
- digits/version.py
This lets you query the version from the command-line (useful for debian packaging) and inside a `setup.py` script (useful for PyPI/conda packaging) without actually having to import DIGITS. We might actually add some code to `__init__.py` someday, and moving this into a separate file now helps with tool maintainability.
Also, rather than simply writing a comment about how the file is supposed to be maintained and updated, I wrote some tests to enforce it.
> Move digits.__version__ into new file and add tests

- digits/extensions/data/objectDetection/README.md
- digits/extensions/data/objectDetection/data.py
- digits/extensions/data/objectDetection/forms.py
- digits/extensions/data/objectDetection/utils.py
* Allow non-numeric filenames (close #940)
* This should also address the issue on Windows where, because symlinks are not supported, the `prepare_kitti_data.py` script creates filenames like `000000039_002994.png`.
* Improve documentation about case sensitivity
* Improve documentation about mapping classes to 0 during dataset creation
> Various small ObjectDetection dataset improvements

- digits/extensions/data/objectDetection/utils.py
*Close #1054*
An empty list of labels is a valid use case.
> Improve handling of empty/invalid object detection label files

- digits/extensions/data/imageGradients/data.py
- digits/extensions/data/imageGradients/forms.py
- digits/extensions/data/imageGradients/inference_template.html
- digits/extensions/data/interface.py
- digits/model/images/generic/test_views.py
- digits/model/images/generic/views.py
- digits/templates/models/images/generic/infer_extension.html
- digits/templates/models/images/generic/show.html
- tools/inference.py
If a dataset extension implements its get_inference_form() method then the standard image inference form is replaced with the extension's inference form:
During inference, an inference dataset is created using the data from the inference form and the appropriate visualization can be used to render the output:
Tasks:
> Modularization of inference

- digits/utils/image.py
```
/home/lyeager/digits/digits/utils/image.py:108:
VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
out[y,x] = image[math.floor(y/ratio), math.floor(x/ratio)]
```
Counter-intuitively, `math.floor()` returns a float.
```py
>>> type(math.floor(0))
<type 'float'>
```
> Supress numpy VisibleDeprecationWarning

- digits/log.py
I can't remember why I had added this originally. Some older version of socketio wasn't interacting well with my custom logger class or something. I want to remove it now because there are a bunch of socketio messages clogging up the testsuite output.
> Remove changes to socketio logger

- digits/model/images/classification/test_views.py
This fixes [some of] the Torch errors we keep getting in the test suite. Before the fix, this command would error out within a few attempts:
while ./digits-test digits/model/images/classification/test_views.py:TestTorchLeNetHdf5Shuffle.test_classify_one_json; do echo 1; done
After the fix, it runs for many minutes without error. @gheinrich why had you added this originally?
> Avoid NaN errors and misclassifications in tests

- docs/API.md
Hello digits maintainers,
I was working through this example and noticed that the cookie file didn't match in the api examples. Was it supposed to be digits.cookie or cookie.tmp? I just changed it to digits.cookie everywhere and it worked for me. Here is a patch if you would like to make them match.
> cookie.tmp replaced by digits.cookie

- digits/templates/home.html
- digits/templates/layout.html
- digits/templates/partials/home/datasets_pane.html
- digits/templates/partials/home/model_pane.html
- digits/templates/partials/home/pretrained_model_pane.html
- digits/views.py
Moved the "Group Jobs" button to be closer to the well containing the table.
Moved the New Dataset and New Model pills to their respective tabs.
The "Upload Pretrained Model" has been moved to a new "Load Model" on the "Pretrained Models" tab.
Changed the "Group" button to be disabled when the "Group Jobs" is unchecked.
From this:
To this:
> Rearranged group elements and pills on the front page

- digits/webapp.py
1. Don't assume `digits/` is in the CWD (found while testing setup.py)
2. Don't use platform-specific paths (doesn't this break on Windows?)
> Fix path given to utils.filesystem.dir_hash()

- digits/templates/layout.html
* Why is `class=brightness` there for just one element?
* I feel like "DIGITS on GitHub" and "DIGITS docs" are nearly redundant
* Capitalization changes
/cc @jmancewicz
> Small changes to the "About" dropdown

- digits/extensions/data/__init__.py
- digits/extensions/data/imageGradients/data.py
- digits/extensions/data/interface.py
- digits/extensions/view/__init__.py
- digits/extensions/view/imageGradients/view.py
- digits/extensions/view/interface.py
- docs/BuildDigits.md
Support for data and view plug-ins. See #921 for examples.
Extra command to support plug-ins:
```
pip install -e $DIGITS_HOME
```
> Add support for plug-ins

- digits-devserver
- digits/__main__.py
This is a totally transparent change because I've left a working `digits-devserver` script in place.
Other projects with a `__main__.py`: [Flask](https://github.com/pallets/flask/blob/master/flask/__main__.py), [pip](https://github.com/pypa/pip/blob/master/pip/__main__.py), [lmdb](https://github.com/dw/py-lmdb/blob/master/lmdb/__main__.py), etc.
I think this change is useful as-is. Future changes/improvements could be:
* Get rid of the `digits-devserver` and `digits-server` scripts entirely
* Refactor `__main__.py` to move most code into another file like `digits/main.py` or `digits/cli.py`
* Change `setup.py` to use `entry_points={'console_scripts'=[...]}` ([blog post](https://chriswarrick.com/blog/2014/09/15/python-apps-the-right-way-entry_points-and-scripts/))
> Move digits-devserver to allow "python -m digits"

- digits/__main__.py
Fix another bug from https://github.com/NVIDIA/DIGITS/pull/1121 - sorry guys.
Without this fix:
```
$ ./digits-devserver -d
___ ___ ___ ___ _____ ___
|   \_ _/ __|_ _|_   _/ __|
| |) | | (_ || |  | | \__ \
|___/___\___|___| |_| |___/ 4.1-dev
2016-09-27 09:20:27 [INFO ] Loaded 3 jobs.
* Restarting with stat
File "/home/lyeager/digits/digits/__main__.py", line 54, in <module>
main()
File "/home/lyeager/digits/digits/__main__.py", line 25, in main
import digits
ImportError: No module named digits
```
> Fix bug in digits/__main__.py

- .travis.yml
*Reverts https://github.com/NVIDIA/DIGITS/commit/918b545693198e58a7d35a20f4d6099781326fd7 from https://github.com/NVIDIA/DIGITS/pull/1113*
It makes it much harder to see why tests failed in the logs.
e.g. https://travis-ci.org/lukeyeager/DIGITS/builds/163531598
> Remove deb build from TravisCI

- digits/model/tasks/torch_train.py
I think this has been broken forever. But it's a bigger deal now that https://github.com/NVIDIA/DIGITS/pull/1091 encourages users to use `CUDA_VISIBLE_DEVICES` to choose the GPUs that will be used in DIGITS.
To test:
1. `export CUDA_VISIBLE_DEVICES=1,0`
2. `./digits-devserver`
3. Train a model with torch
4. You'll see 0 utilization for the selected GPU. `nvidia-smi` will tell you that Torch is using the other GPU.
/cc @gheinrich
> Bugfix - Torch and CUDA_VISIBLE_DEVICES

- packaging/deb/build.sh
Lets you keep multiple builds under `packaging/deb/dist/`
> [DebBuild] Improvements to dist dir

- digits/model/tasks/torch_train.py
I keep running into this issue occasionally. We can keep trying to fix it on the entry-point to DIGITS, but it's simpler to just double-check in the Torch code.
> Torch - use absolute path to wrapper

- .travis.yml
- scripts/travis/install-caffe.sh
- scripts/travis/install-torch.sh
Apparently we only have access to 2 processors on Travis - not 4.
I was hoping this would speed the Torch build up more - it only shaves off a minute or so.
/cc @flx42
> [TravisCI] build parallelism

- digits/config/caffe.py
This typo needed to be fixed so that DIGITS could automatically find Caffe in Windows platforms.
> Correct typo for detecting Windows platform

- MANIFEST.in
/usr/bin/luajit: cannot open /usr/lib/python2.7/dist-packages/digits/tools/torch/wrapper.lua: No such file or directory
> [DebBuild] Include torch code

- examples/medical-imaging/README.md
- examples/semantic-segmentation/fcn_alexnet.deploy.prototxt
Update layer names in prototxt used to perform net surgery.
Doing this will mean Caffe won't attempt to re-use those weights.
This removes the need to rename the layer in the user-defined net description when working with a different number of classes.
> Make it easier to fine-tune FCN-Alexnet for different number of classes

- packaging/deb/templates/pydist-overrides
*Close https://github.com/NVIDIA/DIGITS/issues/1158*
I built a package for scikit-fmm that we'll provide going forward.
> [Debuild] Tell pydist which package provides skfmm

- digits/static/js/digits.js
- digits/static/js/store.js
- digits/store/views.py
- digits/templates/store.html
Making the Model Store page more consistent with the DIGITS front page and adding a download progress bar.
Moving from this look;
To this look;
I also stopped the redirection to the front page after download was complete.
The progress bar is a progress line at the moment, under the model name to save real estate.
> Modelstore ui

- digits/dataset/generic/views.py
- digits/extensions/view/imageSegmentation/view.py
The palette may be `None`when working with grayscale labels.
Fix #1147
> Fix visualization when palette is None

- digits-lint
- plugins/data/imageGradients/digitsDataPluginImageGradients/__init__.py
- plugins/data/imageGradients/digitsDataPluginImageGradients/data.py
- plugins/data/imageGradients/setup.py
- plugins/data/sunnybrook/digitsDataPluginSunnybrook/__init__.py
- plugins/data/sunnybrook/digitsDataPluginSunnybrook/data.py
- plugins/data/sunnybrook/digitsDataPluginSunnybrook/forms.py
- plugins/data/sunnybrook/setup.py
- plugins/view/imageGradients/digitsViewPluginImageGradients/__init__.py
- plugins/view/imageGradients/digitsViewPluginImageGradients/forms.py
- plugins/view/imageGradients/digitsViewPluginImageGradients/view.py
- plugins/view/imageGradients/setup.py
- setup.cfg
Working on https://github.com/NVIDIA/DIGITS/issues/1153
> Fix python lint under plugins/

- digits/extensions/data/objectDetection/data.py
@lukeyeager commented on #1191, and I merged it before seeing the comment.
> Use hasattr when checking for custom_classes

- digits/model/views.py
*Fix #1215*
*Bug comes from https://github.com/NVIDIA/DIGITS/pull/1156*
To reproduce:
* Go to "New Image Classification Model"
* Click on "Previous Networks"
* Pick a network and try to "Customize" it
> Bugfix for customizing previous models

- digits/templates/partials/home/datasets_pane.html
- digits/templates/partials/home/model_pane.html
- digits/templates/partials/home/pretrained_model_pane.html
Jones pointed out that the menus on the right are left aligned allowing them to render offscreen.
> Move New ... menus

- digits/extensions/view/imageSegmentation/app_begin_template.html
- digits/extensions/view/imageSegmentation/static/css/app.css
- digits/extensions/view/imageSegmentation/static/js/app.js
- digits/extensions/view/imageSegmentation/view.py
- digits/extensions/view/imageSegmentation/view_template.html
- digits/utils/image.py
Adding view options for image segmentation. 
The existing Opacity slider changes the opacity of the fill region.
The Mask slider changes the opacity of the non-segmented area. I find this useful to find small segments.
The Threshold slider changes the moves in the distance field around segmentation boundaries.
The Line Width does what you think
Gamma along with the Colormap can make the grey scale medical images a little easier to read.
Also, if the inference feature image comes through as a float array, and PIL won't convert it to an image, then the data is normalized to its range and converted to uint8 so that it will be converted to a PIL.Image.
> Additional image segmentation view options

- plugins/data/imageGradients/digitsDataPluginImageGradients/__init__.py
- plugins/data/sunnybrook/digitsDataPluginSunnybrook/__init__.py
- plugins/data/textClassification/digitsDataPluginTextClassification/__init__.py
- plugins/view/imageGradients/digitsViewPluginImageGradients/__init__.py
- plugins/view/textClassification/digitsViewPluginTextClassification/__init__.py
`__all__` is supposed to contain an array of strings. My bad from https://github.com/NVIDIA/DIGITS/pull/1198.
```
$ python -c "from digitsDataPluginImageGradients import *"
File "<string>", line 1, in <module>
TypeError: Item in ``from list'' not a string
```
> Bugfix: __all__ misused in plugins/

- digits/config/caffe.py
This pull request fixes the problem that happens in Windows platforms when DIGITS tries to find where Caffe is installed, based on CAFFE_ROOT environment variable. Currently, the official Windows Caffe version is (https://github.com/bvlc/caffe/tree/windows), in which once the installation folder is generated (typically it should be a folder called "install" within the Caffe root folder), the caffe.exe executable is in the folder called "bin" and not in "build/tools" and pycaffe files are in the "python" folder inside it.
> Fix Caffe search paths in Windows

- digits/inference/job.py
This happens when you train a Torch model, then restart your server without Torch support and try to run inference on your model.
Throwing a clear error message helps to quickly explain the issue.
> Add explicit error message for missing frameworks

- digits/dataset/images/classification/test_imageset_creator.py
- digits/dataset/images/classification/test_views.py
- digits/model/images/classification/test_views.py
- digits/model/tasks/caffe_train.py
> Fix batch accumulation

- digits/dataset/generic/job.py
- digits/dataset/images/classification/job.py
- digits/dataset/images/generic/job.py
- digits/dataset/images/job.py
- digits/dataset/job.py
- digits/dataset/tasks/analyze_db.py
- digits/dataset/tasks/create_db.py
- digits/dataset/tasks/create_generic_db.py
- digits/dataset/tasks/parse_folder.py
- digits/extensions/data/objectDetection/README.md
- digits/extensions/data/objectDetection/utils.py
- digits/job.py
- digits/model/images/classification/job.py
- digits/model/images/classification/views.py
- digits/model/images/generic/job.py
- digits/model/images/job.py
- digits/model/job.py
- digits/model/tasks/caffe_train.py
- digits/model/tasks/torch_train.py
- digits/model/tasks/train.py
- digits/standard-networks/torch/ImageNet-Training/googlenet.lua
- digits/task.py
- digits/tools/torch/LRPolicy.lua
- digits/tools/torch/data.lua
- digits/utils/image.py
- examples/medical-imaging/README.md
Fix spelling errors in comments with [codespell](https://github.com/lucasdemarchi/codespell/) (thanks to @CDLuminate for pointing this project out in https://github.com/BVLC/caffe/pull/5035).
```
pip install codespell
git ls-files | xargs codespell.py -q2 -w
```
> [Docs] Fix spelling errors in comments

- digits/config/store_option.py
- docs/Configuration.md
With this change, DIGITS will connect to the store as soon as it goes live.
TODO: cherry-pick this into the `master` branch when the store goes live.
> Official model store link

- .travis.yml
- scripts/travis/install-openblas.sh
- scripts/travis/install-torch.sh
*Fix https://github.com/NVIDIA/DIGITS/issues/1173, close https://github.com/NVIDIA/DIGITS/pull/1305*
We had only been building OpenBLAS from source when there was no cached
torch build present on the build machine. That meant you could get a
cached build of Torch which was built against one version of OpenBLAS,
but the system actually installed an older version. This led to memory
corruption and segmentation faults.
> [TravisCI] Cache local OpenBLAS build

- digits/dataset/generic/views.py
> Restrict usage of cmap to labels DB in generic dataset exploration

- docs/ModelStore.md
Provide more details about how to specify the path of Python layer file when using pretrained models.
> Add steps to specify the Python layer file

- docs/BuildCaffe.md
There's really no need to install all of boost.
I've known this for a while, just never got around to updating this doc.
> [Docs] Install minimal boost libs for caffe

- packaging/deb/extras/digits.nginx-site
The 3.0 and 4.0 packages had this. Somehow we lost it for 5.0.
This is a noop change which makes it easier for other packages to customize your DIGITS installation.
> [Packaging] Make nginx site easier to customize programmatically

- docs/StandardDatasets.md
train.txt and test.txt was swapped and shown in the wrong folders for mnist and cifar10 data sets.
> Fix documentation typo. 

- examples/semantic-segmentation/prepare_pascal_voc_data.sh
This just a minor change. But the incorrect #/bin/bash creates problems for users of (t)csh
> Correct shebang for prepare_pascal_voc_data.sh

- scripts/travis/ppa-upload.sh
Caused by https://github.com/NVIDIA/DIGITS/pull/1475.
> `./scripts/travis/ppa-upload.sh: line 22: cd: /home/travis/build/NVIDIA/DIGITS/packaging/deb/dist/*trusty: No such file or directory`
https://travis-ci.org/NVIDIA/DIGITS/jobs/205060340
> Fix shellcheck-related bug in PPA upload script

- digits/dataset/images/classification/views.py
- digits/model/tasks/train.py
This aims to fix #1462 
To test it, I created and moved Image Classification datasets between two machines and everything worked as expected. In addition, I created Classification Models using these datasets in both machines and they worked as expected as well.
The change made in `digits/model/tasks/train.py` was just to make the error more informative.
> Copy labels.txt inside the dataset (Fix #1462)

- digits/dataset/tasks/create_db.py
- digits/static/css/style.css
- digits/templates/datasets/images/classification/show.html
- digits/tools/create_db.py
This aims to fix #1473 
If any `LoadImageError` is raised, dataset pages will look like this:
- notice the `(%d failed to load)` on the **DB Entries**
Datasets without any `LoadImageError` will look exactly the same:
> Fix Distribution Graph

- .travis.yml
Useful for TravisCI builds in forks.
See https://github.com/travis-ci/travis-ci/issues/3412.
> [TravisCI] Add `git fetch --unshallow` for DIST

- digits/utils/image.py
It was annoying when I created a dataset and after a few minutes DIGITS only displayed an error about an image that couldn't load, but it didn't display/log the filename of the image.
The simple change in this pull request ensures that the filename of the problem image is included when displaying / logging the exception.
> Display the filename of the image that caused the exception

- digits/model/tasks/caffe_train.py
Fixes issue #1645, where softmax output was left in 0-1 range (as compared to 0-255 image) which prevented proper visualization. See image for before&after comparison. Changes `digits/model/tasks/caffe_train.py` per @lukeyeager's suggestion.
> Fix softmax visualization by scaling to image range

- digits/frameworks/tensorflow_framework.py
Without this fix to the regular expression, the `re` module will happily
match `lenet.pyc` in addition to `lenet.py`. If your filesystem happens
to return `lenet.pyc` first, then you get a cryptic unicode error when
you try to customize the LeNet network. Presumably you'd get a nasty
error if you tried to actually train with this file as well.
> Tensorflow: fix network customization bug

- digits/model/images/classification/job.py
- digits/model/images/classification/views.py
- digits/model/images/generic/job.py
- digits/model/images/generic/views.py
- digits/model/tasks/tensorflow_train.py
- digits/pretrained_model/job.py
- digits/pretrained_model/tasks/__init__.py
- digits/pretrained_model/tasks/tensorflow_upload.py
- digits/store/views.py
This is because tensorflow requires 3 files: ckpt.data..., ckpt.index, and ckpt.meta for pretrained models. This fix ensures all 3 of them are downloaded and uploaded
> Fixed downloading and uploading tensorflow pretrained models

- examples/gan/network-mnist.py
hist_g + hist_images sometimes cause tf.div error (NaN).
> Prevent NaN in MNIST GAN example.

- digits/templates/home.html
During DIGITS home page loading, raw html codes may appear for short period of time (< 1 sec).  Adding ng-cloak removes that 'flashing' html codes on UI.
> Add ng-cloak to remove flashing html codes during page loading.

- digits/test_views.py
We should keep the idea of timeout assertion in test, but it's hard to guess the test environment and predict a reasonable timeout value.  Remove it until we can find a better way to gauge this test.
> Remove timeout assertion

- digits/views.py
When the length of string, returned by get_title(), is too large, that title in the pulldown menu under 'images' would overflow beyond the menu.  This PR limits that length to 21.
> Avoid overflow text in pulldown menu by limit title to 21 characters

- .travis.yml
- digits/config/tensorflow.py
- scripts/travis/install-caffe.sh
BVLC recently changed caffe_pb2 namespace, which caused incompatibility between nv-caffe and bvlc-caffe.  This PR only tries to make CI pass by build BVLC Caffe from the latest commit before that change.
> Fix BVLC caffe test in Travis CI
