NVIDIA/DIGITS

- tools/create_db.py
> fixed passing of incorrect sizes

- digits/model/forms.py
- digits/model/images/classification/views.py
- digits/model/tasks/caffe_train.py
- digits/model/tasks/train.py
- digits/templates/models/images/classification/new.html
According  to #98 I tried to add solver_type parameter. 
Please check.
> added solver type field

- digits/dataset/images/classification/forms.py
- digits/dataset/images/classification/views.py
- digits/dataset/images/views.py
- digits/dataset/views.py
- digits/job.py
- digits/model/forms.py
- digits/model/images/classification/test_views.py
- digits/model/images/classification/views.py
- digits/model/images/forms.py
- digits/model/job.py
- digits/model/tasks/train.py
- digits/model/views.py
- digits/task.py
- digits/templates/datasets/images/classification/new.html
- digits/templates/home.html
- digits/templates/models/images/classification/new.html
- digits/test_webapp.py
- digits/utils/__init__.py
- digits/utils/forms.py
- digits/utils/routing.py
- digits/views.py
- digits/webapp.py
- docs/API.md
- docs/FlaskRoutes.md
- docs/GettingStarted.md
- docs/generate_flask_api.py
> Add JSON routes for job creation

- .travis.yml
- README.md
- requirements_test.txt
Take 2 on this. Please delete the old pull request.
Fixes graphviz build issue.
> Add travis support (take 2). Closes #28.

- digits/dataset/images/classification/forms.py
- digits/dataset/images/classification/test_imageset_creator.py
- digits/dataset/images/classification/test_views.py
- digits/dataset/images/classification/views.py
- digits/dataset/job.py
- digits/templates/datasets/images/classification/new.html
- digits/test_views.py
- digits/utils/forms.py
- docs/API.md
- docs/FlaskRoutes.md
I would like to add tests in test_webapp.py for this. However I understand we can't inspect the contents of a "ParseFolder" task using the REST API so it's slightly difficult to check whether the min/max values are taken into account.
> Add option to select min/max samples per class - closes #161

- digits/config/config_file.py
- digits/config/edit.py
- digits/dataset/images/classification/job.py
- digits/dataset/images/generic/forms.py
- digits/dataset/images/generic/job.py
- digits/dataset/images/generic/views.py
- digits/model/images/generic/views.py
- digits/model/tasks/caffe_train.py
- digits/status.py
- digits/utils/forms.py
- digits/views.py
- docs/API.md
- docs/FlaskRoutes.md
- scripts/generate_docs.py
- tools/analyze_db.py
None of these are functional changes. Just cleaning up the code.
See previous list of issues here:
https://landscape.io/github/NVIDIA/DIGITS/117/messages
> Fix errors and smells as reported by Landscape

- digits/model/images/classification/views.py
- digits/model/images/generic/views.py
- digits/model/tasks/caffe_train.py
- digits/templates/models/images/classification/classify_one.html
- digits/templates/models/images/generic/infer_one.html
- docs/API.md
- docs/FlaskRoutes.md
See #220. Also made some subtle UI changes.
> Add # of learned parameters to weights vis

- digits/templates/models/images/generic/new.html
> replace generic model epoch field

- digits/dataset/tasks/create_db.py
- tools/create_db.py
- tools/test_create_db.py
I want to merge part of #226 early so that I can put a fix for #242 into `master` while I'm still trying to figure out the HDF5Data layer issues (see https://github.com/NVIDIA/caffe/pull/26).
> Add HDF5 support to create_db.py

- digits/dataset/tasks/create_db.py
- tools/create_db.py
- tools/test_create_db.py
#209 requires a new version of py-lmdb, and it's causing problems for people:
* #242
* https://groups.google.com/d/msg/digits-users/aC0hMoR74uE/KXEEBrpvJgAJ
This PR should help avoid those issues going forward.
> Throw a more helpful error if py-lmdb out of date

- requirements.txt
- tools/create_db.py
Should have been included with #245.
Also remove lzf reference in docs.
> Add h5py to requirements.txt

- digits/status.py
- digits/task.py
Force task progress to 1.0 (100%) when the status is set to Done.
> Force task progress to 1.0 when done

- digits/model/images/classification/test_views.py
- digits/model/images/generic/test_views.py
- digits/model/views.py
- digits/templates/home.html
- digits/templates/models/index.html
- digits/test_views.py
- digits/views.py
*See #195*
Added some tests, cleaned up some HTML and moved the template file location.
> Results browser tweaks

- digits/model/images/classification/views.py
- digits/model/images/generic/views.py
- digits/templates/models/images/classification/classify_many.html
- digits/templates/models/images/classification/classify_one.html
- digits/templates/models/images/classification/show.html
- digits/templates/models/images/classification/top_n.html
- digits/templates/models/images/generic/infer_many.html
- digits/templates/models/images/generic/infer_one.html
- digits/templates/models/images/generic/show.html
Open a new browser tab when you click on `Classify One`, `Classify Many`, `Test One` or `Test Many`.
> Open new tab when testing image[s]

- digits/utils/test_time_filters.py
- digits/utils/time_filters.py
Try to cover everything in utils/time_filters.py.
> test time_filters.py

- digits/static/css/style.css
- digits/templates/layout.html
- digits/views.py
> Strip basedir in autocomplete suggestions

- digits/templates/layout.html
closes #269
See http://bugs.jqueryui.com/ticket/7790
> Keep contents of auto-complete fields when hitting back button

- docs/InstallCaffe.md
- scripts/travis/install-caffe.sh
Also use this version for the Travis build
> Recommend NVCaffe v0.13 in docs

- digits/model/images/classification/test_views.py
- digits/model/images/classification/views.py
- digits/model/images/generic/test_views.py
- digits/model/images/generic/views.py
- digits/model/views.py
> Option to reuse original pretrained model

- tools/create_db.py
> Bugfix in tools/create_db.py

- tools/parse_folder.py
- tools/test_parse_folder.py
> Sort subfolders in parse_folder.py

- digits/views.py
`jobs_dir` and `server_name` (if set)
> Add more server info to /index.json

- examples/classification/example.py
> Fix bug in classification example

- digits/dataset/images/classification/test_views.py
- digits/dataset/images/generic/test_views.py
- digits/model/images/classification/test_views.py
- digits/model/images/generic/test_views.py
- digits/templates/job.html
- digits/test_views.py
- digits/views.py
- docs/API.md
- docs/FlaskRoutes.md
*Cleans up #283*
* Combine `edit_job_notes` into `edit_job`
* Add some error checking for dealing with empty values
* Add some basic tests
> Add some tests and error checking for changing job name and notes

- digits/model/tasks/caffe_train.py
Bug introduced in #221.
Reported at https://groups.google.com/d/msg/digits-users/LJu_tLfOHA0
> Don't try to count biases for layers without them

- digits/dataset/images/classification/test_views.py
- digits/dataset/images/generic/test_views.py
- digits/dataset/tasks/create_db.py
- digits/model/images/classification/test_views.py
- digits/model/images/generic/test_views.py
- digits/model/tasks/caffe_train.py
- digits/templates/job.html
- digits/templates/models/images/classification/new.html
- digits/templates/models/images/generic/new.html
- digits/test_views.py
- digits/views.py
- docs/API.md
- docs/FlaskRoutes.md
Cherry-picking commits from #285, #308, #315 and #317.
This will roll up into v2.2.1.
> Cherry-pick fixes into digits-2.2 branch

- digits/config/caffe_option.py
- digits/dataset/images/classification/job.py
- digits/dataset/images/generic/test_lmdb_creator.py
- digits/frameworks/caffe_framework.py
- digits/model/images/classification/test_views.py
- digits/model/images/generic/test_views.py
- digits/model/tasks/caffe_train.py
- tools/analyze_db.py
- tools/create_db.py
- tools/test_analyze_db.py
> Address protobuf PicklingErrors on all platforms

- docs/InstallCaffe.md
> Consolidate apt-get commands for easier copy+paste

- digits/dataset/tasks/analyze_db.py
> Remove debug print statement

- digits/config/caffe_option.py
- digits/utils/__init__.py
- digits/utils/test_utils.py
*Fix #337*
Add lots of tests, too.
> Fix warning with setuptools >= 8.0

- digits/model/images/classification/test_views.py
- digits/standard-networks/torch/lenet-color.lua
- using a color model of LeNet to more accurate discrimination
of color images.
- add more combinations of training parameters (DB backend and shuffle).
- test correct classification of all categories
> More robust Torch image classification test

- digits/model/images/classification/test_views.py
- digits/model/images/generic/test_views.py
GraphViz is listed as optional in the README
> Skip tests which fail because GraphViz is missing

- digits/model/images/generic/test_views.py
> Skip Torch generic model tests if Torch not installed

- digits/dataset/images/classification/test_views.py
- digits/dataset/images/generic/test_views.py
- digits/model/images/classification/test_views.py
- digits/model/images/generic/test_views.py
Yet another Travis build failed due to timeouts, this time on the `master` branch.
https://travis-ci.org/NVIDIA/DIGITS/builds/85583391
> Increase test timeouts

- digits/model/images/generic/test_views.py
- digits/model/tasks/torch_train.py
Lua uses 'inf' to represent infinite numbers. Additionally Torch may use
'nan' in its representation of infinite values in Tensors.
We must catch both cases in the parsing of training and validation
losses.
Add test to verify functionality.
> Fix parsing of infinite loss in Torch

- digits/test_status.py
Stop creating "tmp.p" files in the main DIGITS directory
> Fixup test_status.py

- digits/templates/job_management.html
- digits/templates/job_row.html
> remove ago from running jobs

- tools/torch/data.lua
- tools/torch/main.lua
Using MNIST (45k training samples, 15k validation samples) and LeNet (20 epochs):
original: 118s
new: 91s
Using CIFAR10 (images upscaled to 256x256):
Alexnet (2 epochs) original: 948s
Alexnet (2 epochs) new: 869s
GoogLenet (2 epochs) original: 5280s
GoogLenet (2 epochs) new: 5100s
> Torch multi-threaded data loader

- digits/dataset/images/classification/test_views.py
- digits/dataset/images/classification/views.py
- digits/utils/image.py
*Fix #400*
* Allow exploration of raw LMDB datasets
* Refactor image_to_base64 into embed_image_html in utils.image
* Add some more tests
> Allow exploration of raw LMDB datasets

- tools/torch/data.lua
Doing it from a worker thread is unsafe.
Reference:
https://github.com/deepmind/torch-hdf5/issues/42
> Import HDF5 from main thread

- examples/classification/example.py
fix for classification example, similar to #361
> Deep copy scores in classification example

- tools/torch/data.lua
Implement similar patch to https://github.com/BVLC/caffe/pull/3088
If we can't open the LMDB database, try again with no locking.
If this fails again, throw a human-readable error, for example:
2015-11-11 21:29:33 [INFO ] opening LMDB database: /fast-scratch/gheinrich/ws/digits/digits/jobs/20151111-210842-a4ec/train_db
/fast-scratch/gheinrich/ws/torch/install/bin/luajit: ...nrich/ws/torch/install/share/lua/5.1/threads/threads.lua:264:
[thread 4 callback] /fast-scratch/gheinrich/ws/digits/tools/torch/data.lua:117: Failed to open LMDB database: Permission denied
> Allow opening of read-only LMDB in Torch

- README.md
*See #401*
Update README to reflect changes in #392.
> Update README to use the correct port

- docs/InstallTorch.md
> Update Torch install instructions for DIGITS 3

- .gitignore
- digits/model/images/classification/views.py
- digits/model/images/generic/views.py
- digits/model/views.py
- digits/scheduler.py
- digits/views.py
Just moving the `scheduler.jobs` list from a `list` to a `dict` indexed by `job.id()`.
> Move scheduler.jobs to a dict.

- digits-walkthrough
- requirements_test.txt
*Revert #352*
Make a few small updates/improvements (see second commit).
> Bring back the walkthrough

- digits/dataset/images/classification/job.py
- digits/dataset/tasks/create_db.py
- digits/model/tasks/caffe_train.py
- digits/model/tasks/train.py
- digits/scheduler.py
- digits/templates/models/images/classification/show.html
- digits/templates/models/images/generic/show.html
- digits/webapp.py
Most users shouldn't run into these issues because they should never have jobs lying around with invalid pickle files.
This PR makes error-handling a little more robust (for other errors that will occur in the future) and a little more verbose (so we are motivated to keep adding robustness). It shouldn't change any real functionality.
Before (on my machine):
```
Upgrading CaffeTrainTask to version 3 ...
Upgrading CaffeTrainTask to version 3 ...
Upgrading CaffeTrainTask to version 3 ...
Upgrading CaffeTrainTask to version 3 ...
Upgrading CaffeTrainTask to version 3 ...
Upgrading CaffeTrainTask to version 3 ...
Upgrading CaffeTrainTask to version 3 ...
Upgrading CaffeTrainTask to version 3 ...
Upgrading CaffeTrainTask to version 3 ...
Upgrading CaffeTrainTask to version 3 ...
Upgrading …
```
> Cleanup messages about upgrading/loading previous jobs

- digits/scheduler.py
Fixing some warts in `digits.scheduler`.
See commit messages for details.
> Cleanup scheduler

- digits/dataset/tasks/create_db.py
- digits/templates/datasets/images/classification/show.html
- digits/templates/job.html
*Close #404*
Shouldn't require a page refresh to see these elements.
> Display mean and explore btn when task is done

- digits/model/images/classification/views.py
> Disable colormap for "Top N" feature

- tools/create_db.py
Cherry-pick of #491 for the `master` branch.
> Move image encoding out of main create_db thread (master)

- digits-devserver
- digits/dataset/images/classification/test_views.py
- digits/dataset/images/generic/test_views.py
- digits/model/images/classification/test_views.py
- digits/model/images/generic/test_views.py
- digits/test_scheduler.py
- digits/test_views.py
- digits/webapp.py
By putting it into `digits/webapp.py`, everyone who needs monkey patching gets it. No need for each file to do it themselves.
> Only call gevent.monkey.patch_all() once

- digits/model/images/classification/test_views.py
- digits/model/images/generic/test_views.py
Re-enables running the testsuite file-by-file
./digits-test digits/model/images/classification/test_views.py
> Fix bug from #501

- digits/dataset/images/classification/test_views.py
- digits/dataset/images/generic/test_views.py
- digits/model/images/classification/test_views.py
- digits/model/images/generic/test_views.py
Gives you some more information when/if something goes wrong
> Small improvement to testsuite error reporting

- digits/config/test_prompt.py
- digits/dataset/images/classification/test_views.py
- digits/dataset/images/classification/views.py
- digits/dataset/images/generic/test_lmdb_creator.py
- digits/dataset/images/generic/test_views.py
- digits/dataset/images/views.py
- digits/model/images/classification/test_views.py
- digits/model/images/generic/test_views.py
- digits/utils/image.py
- digits/utils/test_image.py
- examples/siamese/create_db.py
- tools/create_db.py
- tools/test_create_db.py
They were out of sync and this is safer anyway.
> Standardize cStringIO/StringIO imports

- tools/analyze_db.py
> Allow analyze_db tool to read Datums without shape

- digits/model/images/generic/test_views.py
- digits/model/tasks/torch_train.py
- tools/torch/test.lua
- tools/torch/utils.lua
Some model layers in Torch output tables of Tensors. This commit adds support for these layers. This also enables ND tensors in the output.
> Support table of outputs in Torch models

- examples/siamese/create_db.py
> Enable batch writing in order to speed up DB creation.
fix slowliness issue reported in #515 and #486
> Remove extra channel transpose - already done in _save_image()
Fixes one issue reported in #515
> Siamese DB creation fixes

- digits/templates/datasets/images/classification/show.html
- digits/templates/datasets/images/generic/show.html
> Add a missing `dd` tag and fix an unmatched `dt` tag

- nginx.site
> Fix nginx redirection to ports other than 80 (master)

- digits/model/views.py
> Allow non-integer step size in visualize_lr()

- docs/BuildTorchLMDB.md
- scripts/travis/install-torch.sh
> Use last version of lightningmdb wrapper for Torch

- examples/python-layer/README.md
`master` version of https://github.com/NVIDIA/DIGITS/pull/546
> Add warning about Python layers and multi-GPU (master)

- digits/model/tasks/caffe_train.py
*Close https://github.com/NVIDIA/DIGITS/issues/547*
> Fix multistep learning rate parsing

- digits/model/images/classification/test_views.py
- tools/torch/LRPolicy.lua
Add unit test and fix Torch handling of multistep LR policy
fix #547
> Fix Torch handling of multistep LR policy

- examples/classification/README.md
We could avoid these problems with https://github.com/NVIDIA/DIGITS/issues/228.
> Address gotchas with the classification example

- docs/BuildCaffe.md
- docs/BuildDigits.md
- docs/BuildTorch.md
- docs/GettingStarted.md
- docs/InstallCuda.md
- docs/WebInstall.md
- examples/python-layer/README.md
Enough questions have come up that I feel like this deserves its own doc.
> Add documentation for installing CUDA

- docs/InstallCuda.md
I forgot to include this suggestion from @flx42's in https://github.com/NVIDIA/DIGITS/pull/558.
This is a little simpler / easier.
> Use echo/tee to create file at /etc/ld.so.conf.d/

- digits/templates/models/index.html
> Fix links to jobs on job details page

- digits/model/views.py
> Cast to float (not int) when customizing snapshots

- examples/siamese/mnist_siamese_train_test.prototxt
> Fix name of ip2_right bias

- examples/classification/example.py
performance enhancement as per https://github.com/NVIDIA/DIGITS/issues/581
> Classification example np.array performance bottleneck

- README.md
See https://github.com/NVIDIA/DIGITS/pull/276, https://github.com/NVIDIA/DIGITS/pull/443
> Re-delete Landscape.io badge

- digits/model/images/classification/views.py
Also, stop shuffling. No point.
> Fix TopN when top_n > num_images

- digits/frameworks/torch_framework.py
- digits/log.py
- digits/model/tasks/torch_train.py
- digits/scheduler.py
- digits/static/js/socket.io.js
- digits/task.py
- digits/test_status.py
- digits/utils/image.py
- digits/utils/test_time_filters.py
- docs/GettingStarted.md
- examples/fine-tuning/README.md
- examples/python-layer/README.md
I think this is the final typo fix PR. :)
> Fix typos in strings and comments.

- digits/model/images/classification/test_views.py
- digits/model/images/classification/views.py
> Fix ignored image folder in Top-N classification

- digits/views.py
> Sorted autocomplete suggestions

- digits/model/tasks/caffe_train.py
Also save files first, before running sanity checks. Helps if you want to debug manually.
> Sanity check all phases - train/val/deploy

- examples/siamese/README.md
- examples/siamese/create_db.py
> Removed unused parameters in Siamese create_db tool

- requirements.txt
> Fix gevent version to avoid UnicodeError

- digits/model/tasks/caffe_train.py
> Don't sanity check val phase if val set not present

- tools/torch/LRPolicy.lua
"exp", "inv" and "sigmoid" weren't operating as expected
close #662
> Fix Torch LR policy

- scripts/travis/install-torch.sh
Fix errors due to import change on https://github.com/torch/image/commit/8a0596bbb508da33974833e8f075fec5c9738c9e
> Torch: install fs package on Travis

- digits/job.py
> Don't set job event on reload

- digits/templates/models/images/classification/new.html
- digits/templates/models/images/generic/new.html
> Select framework on model cloning

- tools/torch/data.lua
If tds is not installed because e.g. Torch was installed with torch-nv deb package then default to using a regular Lua table to store LMDB keys.
There is a limit of 2GB for heap memory in Luajit so we might not be able to train on some large datasets without tds.
> Default to Lua table if tds not installed

- digits/templates/job_item.html
This addresses the first item in #706.
> change the Done time to be the running rather than elapsed

- digits/templates/models/images/classification/new.html
- digits/templates/models/images/generic/new.html
> Show dataset information on model clone

- digits/views.py
> Update job form data on name edit

- digits/utils/forms.py
> fix optional multi-fields

- digits/model/tasks/caffe_train.py
- digits/utils/image.py
> Fix Torch visualization of color image layers

- digits/model/tasks/torch_train.py
- tools/torch/main.lua
- tools/torch/test.lua
> Dump full model when creating Torch model snapshot

- digits/templates/home.html
- digits/views.py
This will make it easier to add dataset/model types
> Use dictionary for dataset/model options

- .github/CONTRIBUTING.md
Reported here: https://github.com/NVIDIA/DIGITS/pull/751#issuecomment-219793129
Bug comes from: https://github.com/NVIDIA/DIGITS/pull/584
> Fix link to CLA from CONTRIBUTING.md

- digits/model/images/generic/views.py
Somehow this was forgotten in #657
> Remove image file created during infer_one

- digits/model/images/generic/test_views.py
- digits/model/tasks/caffe_train.py
Do a little work to enable all-in-one nets in the generic path. See the added test for the type of network this enables.
> More support for generic all in one nets

- digits/model/images/classification/views.py
- digits/model/images/generic/views.py
Otherwise, the test suite can miss failed tests:
https://github.com/NVIDIA/DIGITS/blob/v3.3.0/digits/model/images/generic/test_views.py#L348
> Return proper HTTP status codes after inference

- .travis.yml
- scripts/travis/install-apt.sh
- scripts/travis/install-caffe.sh
- scripts/travis/install-torch.sh
Brings the build+test time down from ~42 minutes to ~22 minutes. About 10 minutes of the difference comes from the improved Torch build time - they build a lot of dependencies from source.
> TravisCI overhaul

- tools/torch/test.lua
Issue reported by Rombout Karelse on DIGITS users list.
> Fix crop length assertion during Torch inference

- digits/scheduler.py
Follow-up from https://github.com/NVIDIA/DIGITS/pull/767.
See https://github.com/NVIDIA/DIGITS/pull/767#issuecomment-221353355
> Don't show self in related jobs

- examples/python-layer/README.md
Broken since https://github.com/NVIDIA/DIGITS/pull/733
> Update python-layer example for new LeNet

- digits/config/current_config.py
- digits/config/extension_list.py
- digits/extensions/data/__init__.py
- digits/extensions/view/__init__.py
- digits/model/images/generic/views.py
- digits/views.py
Add config options to selectively enable extensions.
Default value comes from code (extension init module).
> Config option for extensions

- digits/dataset/generic/test_views.py
- digits/dataset/images/generic/test_views.py
- digits/model/images/generic/job.py
- digits/model/images/generic/test_views.py
- digits/model/tasks/torch_train.py
- tools/torch/test.lua
> Add tests for models trained on generic datasets

- digits/model/forms.py
- digits/model/tasks/caffe_train.py
Fix bug in https://github.com/NVIDIA/DIGITS/pull/744
> Fix batch accumulation TypeError when unset

- tools/inference.py
The error message contains a reference to self, which is not present since it is outside a class. I propose to remove the self from the error message.
> Update inference.py (bug fix)

- digits/model/tasks/caffe_train.py
> Set weight_decay = base_lr / 100

- digits/model/tasks/caffe_train.py
Forgot to do this in https://github.com/NVIDIA/DIGITS/pull/792
> Change weight_decay for generic nets, too

- digits/dataset/images/classification/forms.py
- digits/templates/layout.html
- digits/views.py
Close #586
fixed white-space in view
fixed if statement problem
> Only allow entering absolute path to textfields with autocomplete

- digits/dataset/generic/test_views.py
- digits/dataset/generic/views.py
- digits/dataset/images/classification/views.py
- digits/dataset/tasks/create_generic_db.py
- digits/templates/datasets/generic/show.html
- digits/templates/datasets/images/explore.html
- digits/utils/lmdbreader.py
- tools/inference.py
Add button to explore **encoded** LMDBs
> Explore generic datasets

- digits/utils/forms.py
The Learning Rate range validator has a min of 0.0 inclusive, but a learning rate of 0 seems bad, (I may be wrong), so, I've added min_inclusive and max_inclusive booleans to that 0 is excluded.
> Allow MultiNumberRange to be inclusive or exclusive

- digits/model/tasks/caffe_train.py
The letter cases of solver types are not always upper case in PyCaffe solvers.  Only SGD can be mapped directly to SGDSolver.  Others have to be mapped via manually-defined dictionary.
In case the solver type is not recognized, throw ValueError.
> Fix incorrect solver type name mapping

- digits/device_query.py
While debugging https://github.com/NVIDIA/nvidia-docker/issues/108, I realized we're not checking some return codes.
> Add some more error checking in device_query

- digits/templates/home.html
The config menu and button could creep out of the container. The menu could get so far out that it wasn't readable.
> Keep the config button and popup within the container width

- digits/utils/forms.py
Assigning @jmancewicz to review and merge
Thanks to @flx42 for the report
> Removing debug print statement

- tools/create_generic_db.py
This moves the reporting of errors that occurred in a reader thread to just after the thread completes.
Doing this avoids dropping an error when trying to add together arrays of different shapes if a reader thread errored because the feature/label shape was not constant.
Assertions are replaced with more meaningful exceptions (helps display the real error in DIGITS UI i.e. instead of showing `AssertionError` we are now showing `ValueError: shape mismatch ...`).
> Improve generic DB creation error reporting

- digits/templates/layout.html
- digits/views.py
*Fix #838*
*Comes from #773*
@IsaacYangSLA Would you be able to try this out for me on windows? Thanks!
> removed forced slash when using autocomplete

- digits/dataset/generic/job.py
- digits/dataset/generic/test_views.py
- digits/model/images/generic/test_views.py
- digits/model/tasks/caffe_train.py
The generic path was left out in #655.
This fixes it and adds tests for the generic path.
> Don't sanity check val phase if val set not present (bis)

- docs/BuildDigits.md
- docs/BuildDigitsWindows.md
A brief readme style document on how to setup DIGITS w/ its dependencies to have a working DIGITS server on Windows.
> Document on building DIGITS on Windows

- digits/device_query.py
> Fix typo in nvml device query error message

- docs/GettingStartedTorch.md
> Update doc to reflect new snapshot loading scheme

- digits/test_device_query.py
Use more sophisticated check for nvml in tests.
Thanks to @flx42 for the report!
> Use get_nvml() in tests

- digits/config/caffe_option.py
OS-X version reporting was hardcoded to 0.11. That means version dependent features were disabled (advanced optimizers f.e.).
New Caffe nicely reports:
```
Tims-Mac-Pro:tools tzaman$  ./caffe --version
caffe version 1.0.0-rc3
```
Old Caffe reports:
```
Tims-Mac-Pro:tools tzaman$ ./caffe --version
caffe
```
After which it would try to do an `ldd` call on the executable, which does not exist in OS-X, and since otool did not yield useful information I have just skip the fallback lib version check.
Close #914.
> Fix for osx version reporting

- digits/model/views.py
Fix #919 
In Windows, tempfile behaves differently than in Linux.
Use BytesIO instead of tempfile since info.json is usually small.
Tested in Windows with default compression (tar.gz) and with curl -XPOST download.zip.  Both worked without issues.
> Fix IOError in Windows when downloading model

- docs/BuildTorch.md
- scripts/travis/install-torch.sh
> Explicitly use Lua LMDB wrapper version 0.9.18.1-1

- .travis.yml
- scripts/travis/bust-cache.sh
- scripts/travis/install-caffe.sh
- scripts/travis/install-torch.sh
This will let us find problems like https://github.com/NVIDIA/DIGITS/issues/908 more quickly.
I thought this was super easy (https://github.com/NVIDIA/DIGITS/pull/788), but realized it took a bit more work (https://github.com/NVIDIA/DIGITS/pull/911).
> Cache travis builds for only one week

- digits/model/images/classification/test_views.py
- digits/model/tasks/caffe_train.py
- digits/task.py
- tools/torch/test.lua
Add a test to detect this bug: https://github.com/NVIDIA/caffe/issues/196 (was https://github.com/NVIDIA/DIGITS/issues/907)
Verifies this fix: https://github.com/NVIDIA/caffe/pull/200
> Test for cpu inference

- digits/dataset/generic/test_views.py
- digits/extensions/data/__init__.py
- digits/extensions/data/imageProcessing/__init__.py
- digits/extensions/data/imageProcessing/data.py
- digits/extensions/data/imageProcessing/forms.py
- digits/extensions/data/imageProcessing/template.html
- digits/extensions/view/__init__.py
- digits/extensions/view/imageOutput/__init__.py
- digits/extensions/view/imageOutput/config_template.html
- digits/extensions/view/imageOutput/forms.py
- digits/extensions/view/imageOutput/view.py
- digits/extensions/view/imageOutput/view_template.html
- digits/inference/job.py
- digits/inference/tasks/inference.py
- digits/model/images/generic/test_views.py
- digits/model/images/generic/views.py
- digits/model/tasks/caffe_train.py
- digits/model/tasks/torch_train.py
- digits/templates/models/images/generic/show.html
- digits/utils/image.py
- tools/inference.py
- tools/torch/data.lua
Caffe and Torch pre-processors are updated to handle the case where the input image dimensions do not match those of the training set.
Depends on #806 and #880
> Support variable input size

- digits/model/views.py
- digits/pretrained_model/job.py
- digits/pretrained_model/tasks/__init__.py
- digits/pretrained_model/tasks/caffe_upload.py
- digits/pretrained_model/tasks/torch_upload.py
- digits/pretrained_model/tasks/upload_pretrained.py
- digits/pretrained_model/test_views.py
- digits/pretrained_model/views.py
- digits/static/js/components/PretrainedModel.js
- digits/static/js/home_app.js
- digits/templates/models/images/classification/show.html
- digits/templates/partials/home/pretrained_model_pane.html
- digits/views.py
depends on #896 . Convert existing training jobs into pretrained models.
> Convert Training Jobs to Pretrained Model Jobs

- examples/object-detection/README.md
> [digits-4.0] docs update

- digits/model/forms.py
- digits/model/images/classification/views.py
- digits/model/images/generic/views.py
- digits/model/tasks/caffe_train.py
- digits/model/tasks/train.py
- digits/templates/models/images/classification/new.html
- digits/templates/models/images/generic/new.html
When RMSProp solver is selected, rms_decay options appears so user can change its default value:
> adds rms_decay option when RMSProp solver is selected

- digits/static/js/home_app.js
- digits/templates/partials/home/pretrained_model_pane.html
- digits/views.py
Trying to keep the drawing decision further down the view path
> move had_labes icon from python to an angularjs directive

- digits/model/views.py
- digits/pretrained_model/views.py
- digits/templates/models/images/generic/show.html
> convert generic tasks to pretrained models

- digits/pretrained_model/tasks/upload_pretrained.py
removed gpu resources from upload pretrained model task
> removed gpu resources from upload pretrained model task

- digits/extensions/view/boundingBox/view.py
- digits/extensions/view/interface.py
- digits/extensions/view/rawData/view.py
> Fix inconsistencies in view interface parameters

- gunicorn_config.py
*Fix #1063*
Bug comes from https://github.com/NVIDIA/DIGITS/pull/965.
> Gunicorn fix - add abspath(curdir) to PATH

- scripts/travis/install-apt.sh
Should shave off a little time.
`python-matplotlib` because https://github.com/NVIDIA/DIGITS/pull/961
`python-gevent-websocket` because https://github.com/NVIDIA/DIGITS/pull/965
> Install a few more deb packages on TravisCI

- digits/static/js/home_app.js
- digits/templates/layout.html
- digits/templates/partials/home/model_pane.html
- digits/templates/partials/home/pretrained_model_pane.html
Internet Explorer was stopping the evaluation of the home page. These changes have it working correctly on IE 11.0.
> Changed a few things so that IE would display the front page correctly

- digits/model/images/classification/test_views.py
Like https://github.com/NVIDIA/DIGITS/pull/1074, this is trying to get rid of all the meaningless TravisCI errors.
> [Tests] More time for data aug model to converge

- digits/utils/forms.py
Use implicit boolean value of field value.
fix #1102
> Fix validate_required_if_set validator

- .gitignore
- digits/.gitignore
Various small improvements to .gitignore
Mostly, it's more explicit about what to ignore under `digits/`
Discovered while working on https://github.com/NVIDIA/DIGITS/pull/1093
> gitignore improvements

- digits/tools/analyze_db.py
I use this little tool all the time and often add a little hack like this in there for debugging.
Example usage:
```
$ ./tools/analyze_db.py --only-count --print-data ~/label_test.lmdb/
2016-09-15 10:41:27 [INFO ] Total entries: 1108
>>> Datum #0 (shape=(1, 19, 16))
[[[    5.      16.       0.       0.       0.       0.       0.       0.
0.       0.       0.       0.       0.       0.       0.       0.  ]
[  495.22   180.06    22.83    17.16     1.67     1.       0.       1.53
0.       1.       3.98     1.53     1.41    -8.88     2.04    62.07]
[  598.73   176.16    27.84    27.51    -1.58     1.       0.      -1.57
0.       0.       3.64     1.67     1.65     0.13     1.88    45.53]
[  366.21   185.06    49.99    28.22     1.84     1.       0.       1.55
0.       1.       4.16     1.55 …
```
> Add --print-data to analyze_db tool

- digits-devserver
- digits/__main__.py
Fix some bugs from https://github.com/NVIDIA/DIGITS/pull/1121
> digits-devserver bugfixes

- digits/gunicorn_config.py
Fix bug from https://github.com/NVIDIA/DIGITS/pull/1093.
> Fix bug in gunicorn_config

- digits/config/log_file.py
Fix a bug in https://github.com/NVIDIA/DIGITS/pull/1091
> Stop deleting logfiles

- docs/UbuntuInstall.md
*(wait to merge until the package is actually updated)*
We'll probably want to cherry-pick this back into the `digits-4.0` branch, too.
> Update the ML repo package name

- packaging/deb/build.sh
Non-functional coding style change: https://github.com/NVIDIA/caffe/pull/246#discussion_r81650354
> [DebBuild] Use shell varsubst instead of sed

- docs/BuildDigits.md
> Add python-pip to DIGITS dependencies

- digits/model/tasks/caffe_train.py
First step to enable python layer file in model store.
> Add python layer file in downloaded files

- digits/config/caffe.py
- digits/views.py
- examples/siamese/create_db.py
- examples/text-classification/create_dataset.py
While investigating https://github.com/NVIDIA/DIGITS/issues/1153, pyflakes pointed out a few real errors (not just style issues).
> Fix errors found with pyflakes

- docs/BuildTorch.md
- scripts/travis/install-torch.sh
Minor changes to torch installation instructions.
/cc @3XX0, @gheinrich
> Luarock installation

- digits/extensions/view/imageSegmentation/view.py
A few lines need to be indented to the correct block
> Fix the image segmentation view line_mask bug

- MANIFEST.in
*Fix https://github.com/NVIDIA/DIGITS/issues/1164*
```diff
$ diff git-archive.txt deb-package-2.txt 
73d72
< ./extensions/data/objectDetection/README.md
121d119
< ./.gitignore
```
> [Packaging] Include extension templates and statics

- scripts/travis/test.sh
> Disable BLAS threading affinity in Travis

- digits/extensions/data/objectDetection/data.py
There's an error reading classification models from before custom_classes was added.
> check for custom_classes

- digits/templates/layout.html
*Fix a bug in https://github.com/NVIDIA/DIGITS/pull/1201*
> Fix path to ace.js files

- digits/extensions/view/imageSegmentation/static/js/app.js
*Lint introduced with #1188*
The lint check was merged after that PR was created and before it was merged, causing a failed build on `master`: https://travis-ci.org/NVIDIA/DIGITS/builds/170938143.
> [Lint] Fix some Javascript lint

- .travis.yml
- MANIFEST.in
- scripts/travis/pypi-upload.sh
*Depends on https://github.com/NVIDIA/DIGITS/pull/1229*
We can't test this for real until we tag something.
Example build: https://travis-ci.org/lukeyeager/DIGITS/jobs/172173617
Example package: https://testpypi.python.org/pypi?name=digits&:action=display
> [Packaging] Upload to PyPI from TravisCI

- plugins/data/sunnybrook/digitsDataPluginSunnybrook/data.py
- plugins/data/sunnybrook/digitsDataPluginSunnybrook/forms.py
- plugins/data/sunnybrook/digitsDataPluginSunnybrook/templates/inference_template.html
> Fix image file entry in Sunnybrook inference form

- examples/medical-imaging/README.md
The Dice metric should be computed for each sample and then averaged across the samples of a batch.
The previous implementation was computing the Dice metric for a full batch, which led to slightly incorrect results.
> Fix calculation of Dice metric in medical imaging example

- digits/dataset/generic/test_views.py
> [Tests] Skip if extension not installed

- digits/static/js/home_app.js
Bugfix for the case where $localStorage.model_fields has not been defined.
> Bugfix in case of missing localStorage.model_fields (#1255)

- digits/static/js/home_app.js
> [Lint] Fix some JS lint

- digits/utils/image.py
> Default to PNG in HTML embeddings

- digits/templates/layout.html
> [UI] Load ace searchbox extension explicitly

- .travis.yml
- digits/dataset/generic/views.py
- digits/extensions/view/imageSegmentation/view.py
> Import pyplot explicitly

- digits/model/tasks/caffe_train.py
This is a rebase of #1262 (which fixed #1240) for the `digits-5.0` branch.
> [Caffe] Fix batch accumulation bug (digits-5.0)

- digits/dataset/generic/test_views.py
- digits/tools/test_create_generic_db.py
https://github.com/NVIDIA/DIGITS/pull/1263 was incomplete.
TravisCI build without plugins and **without** this fix (fails):
https://travis-ci.org/lukeyeager/DIGITS/builds/182047123
TravisCI build without plugins and **with** this fix (passes):
https://travis-ci.org/lukeyeager/DIGITS/builds/182050494
/cc @cliffwoolley
> [Tests] Skip if extension not installed (part 2)

- .travis.yml
To catch bugs like https://github.com/NVIDIA/DIGITS/issues/1256
> [TravisCI] Test all plugins and no plugins

- examples/siamese/mnist_siamese.lua
Broadcast -1 into all elements that equal 0 in original label.
> Fix Siamese example

- examples/text-classification/README.md
> Document a cuDNN workaround for the text classification example

- docs/ModelStore.md
> Fix typo in ModelStore.md

- examples/medical-imaging/README.md
> Fix typo in medical-imaging/README.md

- examples/fine-tuning/create_dataset.sh
- scripts/travis/install-openblas.sh
Thanks to @StevenPuttemans for the bug report at https://github.com/NVIDIA/DIGITS/pull/1475#issuecomment-287744649. My bad!
> Fix a bug introduced when fixing shellcheck lint

- examples/object-detection/README.md
> Fix table formatting in README.md

- docs/UbuntuInstall.md
> [Docs] Document workaround for torch+hdf5 error

- README.md
- docs/UbuntuInstall.md
Close https://github.com/NVIDIA/DIGITS/issues/1545.
> [Docs] Update for 5.0 debs and Ubuntu 16.04 support

- README.md
- digits/config/store_option.py
- docs/Configuration.md
- docs/UbuntuInstall.md
Now that DIGITS 5.0 is officially released, here's the merge I've been putting off.
> Merge digits 5.0 into master

- digits/dataset/images/generic/test_lmdb_creator.py
- digits/standard-networks/tensorflow/googlenet.py
- digits/static/js/home_app.js
- digits/templates/home.html
- examples/fine-tuning/lenet-fine-tune-tf.py
- examples/regression/README.md
- examples/regression/regression-TF.py
> Bug fix changes

- README.md
@lukeyeager for review and approval please
> changed the installation targets in documentation for 6.0 RC

- digits/config/store_option.py
- docs/ModelStore.md
Update document and codes to point to new public model store URL.
> Update ModelStore URL to 6.0

- digits/templates/models/images/generic/show.html
> Fix 404 error for /datasets/inference-form/... from #1888

- digits/tools/tensorflow/main.py
Prevent freezing TF graph in non-classification task.
> Fix output_tensor in non-classification task

- digits/dataset/images/classification/views.py
Fix type mismatch on dataset distribution on each label.
> Fix label distribution and its view page
